<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 4 Modelos Estacionales en Series de Tiempo | Series de Tiempo - Predicción de Precios de Frutas y Verduras en Nepal</title>
  <meta name="description" content="Análisis y predicción de precios de frutas y verduras en Nepal usando técnicas de series de tiempo y machine learning." />
  <meta name="generator" content="bookdown 0.45 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 4 Modelos Estacionales en Series de Tiempo | Series de Tiempo - Predicción de Precios de Frutas y Verduras en Nepal" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Análisis y predicción de precios de frutas y verduras en Nepal usando técnicas de series de tiempo y machine learning." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 4 Modelos Estacionales en Series de Tiempo | Series de Tiempo - Predicción de Precios de Frutas y Verduras en Nepal" />
  
  <meta name="twitter:description" content="Análisis y predicción de precios de frutas y verduras en Nepal usando técnicas de series de tiempo y machine learning." />
  

<meta name="author" content="Grupo 2" />


<meta name="date" content="2025-11-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="pronóstico-de-demanda-holtwinters.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html"><i class="fa fa-check"></i><b>2</b> EDA y Análisis de Series de tiempo</a>
<ul>
<li class="chapter" data-level="2.0.1" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#cargue-de-datos"><i class="fa fa-check"></i><b>2.0.1</b> <strong>Cargue de Datos</strong></a></li>
<li class="chapter" data-level="2.0.2" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#primera-visualización-de-los-datos"><i class="fa fa-check"></i><b>2.0.2</b> <strong>Primera Visualización de los datos</strong></a></li>
<li class="chapter" data-level="2.0.3" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#datos-faltantes-y-duplicados"><i class="fa fa-check"></i><b>2.0.3</b> <strong>Datos faltantes y duplicados</strong></a></li>
<li class="chapter" data-level="2.0.4" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#análisis-univariado"><i class="fa fa-check"></i><b>2.0.4</b> <strong>Análisis Univariado</strong></a></li>
<li class="chapter" data-level="2.0.5" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#análisis-bivariado"><i class="fa fa-check"></i><b>2.0.5</b> <strong>Análisis Bivariado</strong></a></li>
<li class="chapter" data-level="2.0.6" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#correlación-de-los-datos"><i class="fa fa-check"></i><b>2.0.6</b> <strong>Correlación de los datos</strong></a></li>
<li class="chapter" data-level="2.1" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#analisis-de-series-de-tiempo"><i class="fa fa-check"></i><b>2.1</b> <strong>Analisis de series de tiempo</strong></a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#serie-basica-y-acf"><i class="fa fa-check"></i><b>2.1.1</b> <strong>Serie basica y ACF</strong></a></li>
<li class="chapter" data-level="2.1.2" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#promedios-moviles-evidencia-de-suavizado"><i class="fa fa-check"></i><b>2.1.2</b> <strong>Promedios moviles (evidencia de suavizado)</strong></a></li>
<li class="chapter" data-level="2.1.3" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#rezagos-lags-y-dependencia-temporal"><i class="fa fa-check"></i><b>2.1.3</b> <strong>Rezagos (lags) y dependencia temporal</strong></a></li>
<li class="chapter" data-level="2.1.4" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#estacionalidad-descomposicion-stl"><i class="fa fa-check"></i><b>2.1.4</b> <strong>Estacionalidad (descomposicion STL)</strong></a></li>
<li class="chapter" data-level="2.1.5" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#estacionariedad-y-diferenciación"><i class="fa fa-check"></i><b>2.1.5</b> <strong>Estacionariedad y diferenciación</strong></a></li>
<li class="chapter" data-level="2.1.6" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#verificación-de-estacionariedad-adf-test"><i class="fa fa-check"></i><b>2.1.6</b> <strong>Verificación de estacionariedad (ADF Test)</strong></a></li>
<li class="chapter" data-level="2.1.7" data-path="eda-y-análisis-de-series-de-tiempo.html"><a href="eda-y-análisis-de-series-de-tiempo.html#interpretacion"><i class="fa fa-check"></i><b>2.1.7</b> <strong>Interpretacion</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html"><i class="fa fa-check"></i><b>3</b> <strong>Pronóstico de Demanda HoltWinters</strong></a>
<ul>
<li class="chapter" data-level="3.1" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#analisis-de-series-de-tiempo-1"><i class="fa fa-check"></i><b>3.1</b> <strong>Analisis de series de tiempo</strong></a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#selección-del-item-objetivo"><i class="fa fa-check"></i><b>3.1.1</b> <strong>Selección del item objetivo</strong></a></li>
<li class="chapter" data-level="3.1.2" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#serie-basica-y-acf-1"><i class="fa fa-check"></i><b>3.1.2</b> <strong>Serie basica y ACF</strong></a></li>
<li class="chapter" data-level="3.1.3" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#promedios-moviles-evidencia-de-suavizado-1"><i class="fa fa-check"></i><b>3.1.3</b> <strong>Promedios moviles (evidencia de suavizado)</strong></a></li>
<li class="chapter" data-level="3.1.4" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#rezagos-lags-y-dependencia-temporal-1"><i class="fa fa-check"></i><b>3.1.4</b> <strong>Rezagos (lags) y dependencia temporal</strong></a></li>
<li class="chapter" data-level="3.1.5" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#estacionalidad-descomposicion-stl-1"><i class="fa fa-check"></i><b>3.1.5</b> <strong>Estacionalidad (descomposicion STL)</strong></a></li>
<li class="chapter" data-level="3.1.6" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#análisis-conglomerado"><i class="fa fa-check"></i><b>3.1.6</b> <strong>Análisis Conglomerado</strong></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#estacionariedad-y-diferenciación-1"><i class="fa fa-check"></i><b>3.2</b> <strong>Estacionariedad y diferenciación</strong></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#verificación-de-estacionariedad-adf-test-1"><i class="fa fa-check"></i><b>3.2.1</b> <strong>Verificación de estacionariedad (ADF Test)</strong></a></li>
<li class="chapter" data-level="3.2.2" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#interpretacion-1"><i class="fa fa-check"></i><b>3.2.2</b> <strong>Interpretacion</strong></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#suavizamiento-y-holt-winters-sobre-la-variable-tiempo"><i class="fa fa-check"></i><b>3.3</b> <strong>Suavizamiento y Holt-Winters sobre la variable tiempo</strong></a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#particion-de-entrenamiento-prueba"><i class="fa fa-check"></i><b>3.3.1</b> <strong>Particion de entrenamiento /prueba</strong></a></li>
<li class="chapter" data-level="3.3.2" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#agregación-semanal"><i class="fa fa-check"></i><b>3.3.2</b> <strong>Agregación semanal</strong></a></li>
<li class="chapter" data-level="3.3.3" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#modelos-de-suavizamiento-y-holt-winters-en-serie-semanal"><i class="fa fa-check"></i><b>3.3.3</b> <strong>Modelos de suavizamiento y Holt-Winters en serie semanal</strong></a></li>
<li class="chapter" data-level="3.3.4" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#comparación-de-precisión-fuera-de-muestra"><i class="fa fa-check"></i><b>3.3.4</b> <strong>Comparación de precisión fuera de muestra</strong></a></li>
<li class="chapter" data-level="3.3.5" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#diagnostico-de-residuos"><i class="fa fa-check"></i><b>3.3.5</b> <strong>Diagnostico de residuos</strong></a></li>
<li class="chapter" data-level="3.3.6" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#pronostico-final"><i class="fa fa-check"></i><b>3.3.6</b> <strong>Pronostico final</strong></a></li>
<li class="chapter" data-level="3.3.7" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#conclusiones"><i class="fa fa-check"></i><b>3.3.7</b> Conclusiones</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#desarrollo-metodológico-y-justificación-de-decisiones"><i class="fa fa-check"></i><b>3.4</b> <strong>Desarrollo metodológico y justificación de decisiones</strong></a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#ajuste-de-la-frecuencia-temporal"><i class="fa fa-check"></i><b>3.4.1</b> Ajuste de la frecuencia temporal</a></li>
<li class="chapter" data-level="3.4.2" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#modelos-aplicados"><i class="fa fa-check"></i><b>3.4.2</b> Modelos aplicados</a></li>
<li class="chapter" data-level="3.4.3" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#validación-del-modelo"><i class="fa fa-check"></i><b>3.4.3</b> Validación del modelo</a></li>
<li class="chapter" data-level="3.4.4" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#diagnóstico-de-residuos"><i class="fa fa-check"></i><b>3.4.4</b> Diagnóstico de residuos</a></li>
<li class="chapter" data-level="3.4.5" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#pronóstico-final"><i class="fa fa-check"></i><b>3.4.5</b> Pronóstico final</a></li>
<li class="chapter" data-level="3.4.6" data-path="pronóstico-de-demanda-holtwinters.html"><a href="pronóstico-de-demanda-holtwinters.html#conclusión-integradora"><i class="fa fa-check"></i><b>3.4.6</b> Conclusión integradora</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html"><i class="fa fa-check"></i><b>4</b> <strong>Modelos Estacionales en Series de Tiempo</strong></a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#exploración-inicial-de-datos"><i class="fa fa-check"></i><b>4.1</b> <strong>1. Exploración inicial de datos</strong></a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#lectura-de-datos"><i class="fa fa-check"></i><b>4.1.1</b> <strong>Lectura de datos</strong></a></li>
<li class="chapter" data-level="4.1.2" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#transformación-inicial-de-datos"><i class="fa fa-check"></i><b>4.1.2</b> <strong>Transformación inicial de datos</strong></a></li>
<li class="chapter" data-level="4.1.3" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#datos-nulos-y-duplicados"><i class="fa fa-check"></i><b>4.1.3</b> <strong>Datos nulos y duplicados</strong></a></li>
<li class="chapter" data-level="4.1.4" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#análisis-univariado-1"><i class="fa fa-check"></i><b>4.1.4</b> <strong>Análisis Univariado</strong></a></li>
<li class="chapter" data-level="4.1.5" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#análisis-bivariado-1"><i class="fa fa-check"></i><b>4.1.5</b> <strong>Análisis Bivariado</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#analisis-de-series-de-tiempo-2"><i class="fa fa-check"></i><b>4.2</b> <strong>1.1 Analisis de series de tiempo</strong></a></li>
<li class="chapter" data-level="4.3" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#serie-basica-y-acf-2"><i class="fa fa-check"></i><b>4.3</b> <strong>1.2 Serie basica y ACF</strong></a></li>
<li class="chapter" data-level="4.4" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#suavizamiento-temporal"><i class="fa fa-check"></i><b>4.4</b> <strong>2. Suavizamiento temporal</strong></a></li>
<li class="chapter" data-level="4.5" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#promedios-moviles-evidencia-de-suavizado-2"><i class="fa fa-check"></i><b>4.5</b> <strong>2.1 Promedios moviles (evidencia de suavizado)</strong></a></li>
<li class="chapter" data-level="4.6" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#promedios-móviles-7-y-30-base-r-png-include"><i class="fa fa-check"></i><b>4.6</b> <strong>2.2 Promedios móviles (7 y 30) — Base R + PNG + include</strong></a></li>
<li class="chapter" data-level="4.7" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#serie-básica-ts-base-r-png-include"><i class="fa fa-check"></i><b>4.7</b> <strong>2.3 Serie básica (ts) — Base R + PNG + include</strong></a></li>
<li class="chapter" data-level="4.8" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#rezagos-lags-y-dependencia-temporal-2"><i class="fa fa-check"></i><b>4.8</b> <strong>2.4 Rezagos (lags) y dependencia temporal</strong></a></li>
<li class="chapter" data-level="4.9" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#estacionalidad-descomposicion-stl-2"><i class="fa fa-check"></i><b>4.9</b> <strong>2.5 Estacionalidad (descomposicion STL)</strong></a></li>
<li class="chapter" data-level="4.10" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#estacionariedad-y-diferenciación-2"><i class="fa fa-check"></i><b>4.10</b> <strong>Estacionariedad y diferenciación</strong></a></li>
<li class="chapter" data-level="4.11" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#verificación-de-estacionariedad-adf-test-2"><i class="fa fa-check"></i><b>4.11</b> <strong>Verificación de estacionariedad (ADF Test)</strong></a></li>
<li class="chapter" data-level="4.12" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#interpretacion-2"><i class="fa fa-check"></i><b>4.12</b> <strong>Interpretacion</strong></a></li>
<li class="chapter" data-level="4.13" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#ajuste-del-modelo-arima"><i class="fa fa-check"></i><b>4.13</b> <strong>3. AJUSTE DEL MODELO ARIMA</strong></a></li>
<li class="chapter" data-level="4.14" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#criterios-de-selección"><i class="fa fa-check"></i><b>4.14</b> <strong>3.1 Criterios de selección</strong></a></li>
<li class="chapter" data-level="4.15" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#suavizamiento-y-holt-winters-sobre-la-variable-tiempo-1"><i class="fa fa-check"></i><b>4.15</b> <strong>3.2 Suavizamiento y Holt-Winters sobre la variable tiempo</strong></a></li>
<li class="chapter" data-level="4.16" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#particion-de-entrenamiento-prueba-1"><i class="fa fa-check"></i><b>4.16</b> <strong>Particion de entrenamiento /prueba</strong></a></li>
<li class="chapter" data-level="4.17" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#modelos-de-suavizamiento-y-holt-winters-en-serie-semanal-1"><i class="fa fa-check"></i><b>4.17</b> <strong>Modelos de suavizamiento y Holt-Winters en serie semanal</strong></a></li>
<li class="chapter" data-level="4.18" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#comparación-de-presición-fuera-de-muestra"><i class="fa fa-check"></i><b>4.18</b> <strong>Comparación de presición fuera de muestra</strong></a></li>
<li class="chapter" data-level="4.19" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#diagnostico-de-residuos-1"><i class="fa fa-check"></i><b>4.19</b> <strong>Diagnostico de residuos</strong></a></li>
<li class="chapter" data-level="4.20" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#pronostico-final-1"><i class="fa fa-check"></i><b>4.20</b> <strong>Pronostico final</strong></a></li>
<li class="chapter" data-level="4.21" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#conclusiones-1"><i class="fa fa-check"></i><b>4.21</b> <strong>Conclusiones</strong></a></li>
<li class="chapter" data-level="4.22" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#desarrollo-metodológico-y-justificación-de-decisiones-1"><i class="fa fa-check"></i><b>4.22</b> <strong>Desarrollo metodológico y justificación de decisiones</strong></a></li>
<li class="chapter" data-level="4.23" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#ajuste-de-la-frecuencia-temporal-1"><i class="fa fa-check"></i><b>4.23</b> <strong>Ajuste de la frecuencia temporal</strong></a></li>
<li class="chapter" data-level="4.24" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#modelos-aplicados-1"><i class="fa fa-check"></i><b>4.24</b> <strong>Modelos aplicados</strong></a></li>
<li class="chapter" data-level="4.25" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#validación-del-modelo-1"><i class="fa fa-check"></i><b>4.25</b> <strong>Validación del modelo</strong></a></li>
<li class="chapter" data-level="4.26" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#diagnóstico-de-residuos-1"><i class="fa fa-check"></i><b>4.26</b> <strong>Diagnóstico de residuos</strong></a></li>
<li class="chapter" data-level="4.27" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#pronóstico-final-1"><i class="fa fa-check"></i><b>4.27</b> <strong>Pronóstico final</strong></a></li>
<li class="chapter" data-level="4.28" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#conclusión-integradora-1"><i class="fa fa-check"></i><b>4.28</b> <strong>Conclusión integradora</strong></a></li>
<li class="chapter" data-level="4.29" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#ajuste-e-interpretación-del-modelo-arimasarima---box-jenkins-arima"><i class="fa fa-check"></i><b>4.29</b> <strong>4. Ajuste e interpretación del modelo ARIMA/SARIMA - Box-Jenkins (ARIMA)</strong></a></li>
<li class="chapter" data-level="4.30" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#pronostico-a-h-pasos-y-metricas-rmsemaemape"><i class="fa fa-check"></i><b>4.30</b> <strong>Pronostico a h pasos y metricas RMSE/MAE/MAPE</strong></a></li>
<li class="chapter" data-level="4.31" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#diagnostico-de-residuos-2"><i class="fa fa-check"></i><b>4.31</b> <strong>Diagnostico de residuos</strong></a></li>
<li class="chapter" data-level="4.32" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#pronostico-final-sarima-10001052"><i class="fa fa-check"></i><b>4.32</b> <strong>Pronostico final Sarima (1,0,0)(0,1,0)[52]</strong></a></li>
<li class="chapter" data-level="4.33" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#interpretación-del-modelo"><i class="fa fa-check"></i><b>4.33</b> <strong>4.1 Interpretación del modelo</strong></a></li>
<li class="chapter" data-level="4.34" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#reflexión-y-justificación-del-proceso-boxjenkins"><i class="fa fa-check"></i><b>4.34</b> <strong>4.2 Reflexión y justificación del proceso Box–Jenkins</strong></a></li>
<li class="chapter" data-level="4.35" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#ajustes-metodológicos-y-rendimiento-computacional"><i class="fa fa-check"></i><b>4.35</b> <strong>4.3 Ajustes metodológicos y rendimiento computacional</strong></a></li>
<li class="chapter" data-level="4.36" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#evaluación-del-modelo"><i class="fa fa-check"></i><b>4.36</b> <strong>4.4 Evaluación del modelo</strong></a></li>
<li class="chapter" data-level="4.37" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#reflexión-metodológica-final"><i class="fa fa-check"></i><b>4.37</b> <strong>4.5 Reflexión metodológica final</strong></a></li>
<li class="chapter" data-level="4.38" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#evaluación-del-modelo-1"><i class="fa fa-check"></i><b>4.38</b> <strong>5. EVALUACIÓN DEL MODELO</strong></a></li>
<li class="chapter" data-level="4.39" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#pronostico-y-conclusiones"><i class="fa fa-check"></i><b>4.39</b> <strong>6. PRONOSTICO Y CONCLUSIONES</strong></a></li>
<li class="chapter" data-level="4.40" data-path="modelos-estacionales-en-series-de-tiempo.html"><a href="modelos-estacionales-en-series-de-tiempo.html#conclusiones-generales-finales"><i class="fa fa-check"></i><b>4.40</b> <strong>7. CONCLUSIONES GENERALES FINALES</strong></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Series de Tiempo - Predicción de Precios de Frutas y Verduras en Nepal</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelos-estacionales-en-series-de-tiempo" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Capítulo 4</span> <strong>Modelos Estacionales en Series de Tiempo</strong><a href="modelos-estacionales-en-series-de-tiempo.html#modelos-estacionales-en-series-de-tiempo" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Realizaremos nuestro analisis con un conjunto de datos de precios agrícolas proveniente del mercado de Kalimati (Nepal). Este dataset incluye información diaria sobre productos agrícolas, sus precios mínimos, máximos y promedio. A partir de estos datos se realizará un análisis exploratorio y un estudio de comportamiento temporal de los precios.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb87-1" tabindex="-1"></a>csv_file <span class="ot">&lt;-</span> <span class="st">&quot;C:/Users/Steba/OneDrive/Escritorio/kalimati_tarkari_dataset (2).csv&quot;</span></span></code></pre></div>
<div id="exploración-inicial-de-datos" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> <strong>1. Exploración inicial de datos</strong><a href="modelos-estacionales-en-series-de-tiempo.html#exploración-inicial-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El conjunto de datos analizado corresponde a registros diarios de precios de productos agrícolas del mercado de Kalimati (Nepal). Para el caso del producto agrícola analizado “Potato Red”, se estandarizaron nombres de variables y se mapearon columnas clave (Commodity, Date, Minimum, Maximum, Average).
Se realizaron verificaciones de tipo y consistencia (fechas válidas, numéricos no negativos, duplicados) y un análisis descriptivo de la variable de interés (Average), complementado con gráficos de distribución.</p>
<p>Hallazgos principales. La distribución de precios promedio presentó una leve asimetría positiva, consistente con valores ocasionalmente altos. Las medidas de tendencia central (media y mediana) y de dispersión (desviación estándar y rango) indicaron una variabilidad moderada, coherente con mercados agrícolas con choques transitorios en oferta (cosecha, clima, logística).</p>
<div id="lectura-de-datos" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> <strong>Lectura de datos</strong><a href="modelos-estacionales-en-series-de-tiempo.html#lectura-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-1" tabindex="-1"></a><span class="co"># Leer datos</span></span>
<span id="cb88-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-2" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(csv_file, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb88-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-3" tabindex="-1"></a></span>
<span id="cb88-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-4" tabindex="-1"></a><span class="co"># Estandarizar nombres a snake para facilitar mapeo</span></span>
<span id="cb88-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-5" tabindex="-1"></a>nms <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">gsub</span>(<span class="st">&quot;[^a-zA-Z0-9]+&quot;</span>, <span class="st">&quot;_&quot;</span>, <span class="fu">names</span>(data_raw)))</span>
<span id="cb88-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-6" tabindex="-1"></a></span>
<span id="cb88-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-7" tabindex="-1"></a><span class="co"># Intentar mapear columnas canonicas (Commodity / Date / Minimum / Maximum / Average)</span></span>
<span id="cb88-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-8" tabindex="-1"></a>df <span class="ot">&lt;-</span> data_raw</span>
<span id="cb88-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-9" tabindex="-1"></a><span class="fu">names</span>(df) <span class="ot">&lt;-</span> nms</span>
<span id="cb88-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-10" tabindex="-1"></a></span>
<span id="cb88-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-11" tabindex="-1"></a><span class="co"># Mapeo flexible (case-insensitive)</span></span>
<span id="cb88-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-12" tabindex="-1"></a>pick_first <span class="ot">&lt;-</span> <span class="cf">function</span>(cands) {</span>
<span id="cb88-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-13" tabindex="-1"></a>hit <span class="ot">&lt;-</span> <span class="fu">intersect</span>(cands, <span class="fu">names</span>(df))</span>
<span id="cb88-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-14" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(hit) <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">return</span>(<span class="cn">NA_character_</span>) <span class="cf">else</span> <span class="fu">return</span>(hit[<span class="dv">1</span>])</span>
<span id="cb88-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-15" tabindex="-1"></a>}</span>
<span id="cb88-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-16" tabindex="-1"></a></span>
<span id="cb88-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-17" tabindex="-1"></a>col_commodity <span class="ot">&lt;-</span> <span class="fu">pick_first</span>(<span class="fu">c</span>(<span class="st">&quot;commodity&quot;</span>,<span class="st">&quot;item&quot;</span>,<span class="st">&quot;product&quot;</span>,<span class="st">&quot;variety&quot;</span>,<span class="st">&quot;name&quot;</span>))</span>
<span id="cb88-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-18" tabindex="-1"></a>col_date      <span class="ot">&lt;-</span> <span class="fu">pick_first</span>(<span class="fu">c</span>(<span class="st">&quot;date&quot;</span>,<span class="st">&quot;fecha&quot;</span>,<span class="st">&quot;day&quot;</span>))</span>
<span id="cb88-19"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-19" tabindex="-1"></a>col_min       <span class="ot">&lt;-</span> <span class="fu">pick_first</span>(<span class="fu">c</span>(<span class="st">&quot;minimum&quot;</span>,<span class="st">&quot;min&quot;</span>,<span class="st">&quot;min_price&quot;</span>,<span class="st">&quot;price_min&quot;</span>))</span>
<span id="cb88-20"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-20" tabindex="-1"></a>col_max       <span class="ot">&lt;-</span> <span class="fu">pick_first</span>(<span class="fu">c</span>(<span class="st">&quot;maximum&quot;</span>,<span class="st">&quot;max&quot;</span>,<span class="st">&quot;max_price&quot;</span>,<span class="st">&quot;price_max&quot;</span>))</span>
<span id="cb88-21"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-21" tabindex="-1"></a>col_avg       <span class="ot">&lt;-</span> <span class="fu">pick_first</span>(<span class="fu">c</span>(<span class="st">&quot;average&quot;</span>,<span class="st">&quot;avg&quot;</span>,<span class="st">&quot;avg_price&quot;</span>,<span class="st">&quot;price_avg&quot;</span>,<span class="st">&quot;mean_price&quot;</span>))</span>
<span id="cb88-22"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-22" tabindex="-1"></a></span>
<span id="cb88-23"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-23" tabindex="-1"></a>req <span class="ot">&lt;-</span> <span class="fu">c</span>(col_commodity, col_date, col_min, col_max, col_avg)</span>
<span id="cb88-24"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-24" tabindex="-1"></a></span>
<span id="cb88-25"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-25" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">any</span>(<span class="fu">is.na</span>(req))) {</span>
<span id="cb88-26"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-26" tabindex="-1"></a><span class="fu">stop</span>(<span class="st">&quot;No fue posible mapear columnas clave (commodity/date/min/max/average). Revisa nombres del CSV: &quot;</span>,</span>
<span id="cb88-27"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-27" tabindex="-1"></a><span class="fu">paste</span>(<span class="fu">names</span>(df), <span class="at">collapse =</span> <span class="st">&quot;, &quot;</span>))</span>
<span id="cb88-28"><a href="modelos-estacionales-en-series-de-tiempo.html#cb88-28" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb89-1" tabindex="-1"></a><span class="co"># --- Cargar librerías necesarias ---</span></span>
<span id="cb89-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb89-2" tabindex="-1"></a>libs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;dplyr&quot;</span>, <span class="st">&quot;tidyr&quot;</span>, <span class="st">&quot;lubridate&quot;</span>, <span class="st">&quot;stringr&quot;</span>, <span class="st">&quot;tseries&quot;</span>)</span>
<span id="cb89-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb89-3" tabindex="-1"></a><span class="cf">for</span> (pkg <span class="cf">in</span> libs) {</span>
<span id="cb89-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb89-4" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(pkg, <span class="at">character.only =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb89-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb89-5" tabindex="-1"></a>    <span class="fu">install.packages</span>(pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb89-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb89-6" tabindex="-1"></a>    <span class="fu">library</span>(pkg, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb89-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb89-7" tabindex="-1"></a>  }</span>
<span id="cb89-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb89-8" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## Loading required package: dplyr</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 4.3.3</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre><code>## Loading required package: tidyr</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 4.3.3</code></pre>
<pre><code>## Loading required package: lubridate</code></pre>
<pre><code>## Warning: package &#39;lubridate&#39; was built under R version 4.3.3</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<pre><code>## Loading required package: stringr</code></pre>
<pre><code>## Warning: package &#39;stringr&#39; was built under R version 4.3.3</code></pre>
<pre><code>## Loading required package: tseries</code></pre>
<pre><code>## Warning: package &#39;tseries&#39; was built under R version 4.3.3</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb106-1" tabindex="-1"></a><span class="co"># Asegurar el operador %&gt;% disponible</span></span>
<span id="cb106-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb106-2" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">exists</span>(<span class="st">&quot;%&gt;%&quot;</span>)) {</span>
<span id="cb106-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb106-3" tabindex="-1"></a>  <span class="fu">library</span>(magrittr)</span>
<span id="cb106-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb106-4" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="transformación-inicial-de-datos" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> <strong>Transformación inicial de datos</strong><a href="modelos-estacionales-en-series-de-tiempo.html#transformación-inicial-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb107-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-2" tabindex="-1"></a><span class="fu">transmute</span>(</span>
<span id="cb107-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-3" tabindex="-1"></a><span class="at">Commodity =</span> .data[[col_commodity]],</span>
<span id="cb107-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-4" tabindex="-1"></a><span class="at">Date      =</span> <span class="fu">as.Date</span>(.data[[col_date]]),</span>
<span id="cb107-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-5" tabindex="-1"></a><span class="at">Unit      =</span> <span class="cn">NA_character_</span>,     </span>
<span id="cb107-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-6" tabindex="-1"></a><span class="at">Minimum   =</span> <span class="fu">as.numeric</span>(.data[[col_min]]),</span>
<span id="cb107-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-7" tabindex="-1"></a><span class="at">Maximum   =</span> <span class="fu">as.numeric</span>(.data[[col_max]]),</span>
<span id="cb107-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-8" tabindex="-1"></a><span class="at">Average   =</span> <span class="fu">as.numeric</span>(.data[[col_avg]])</span>
<span id="cb107-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-9" tabindex="-1"></a>)</span>
<span id="cb107-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-10" tabindex="-1"></a></span>
<span id="cb107-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-11" tabindex="-1"></a><span class="co"># Chequeos basicos</span></span>
<span id="cb107-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb107-12" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">inherits</span>(data<span class="sc">$</span>Date, <span class="st">&quot;Date&quot;</span>))</span></code></pre></div>
<p>###<strong>Vista previa de los datos</strong></p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb108-1" tabindex="-1"></a><span class="co"># Vista previa y estructura</span></span>
<span id="cb108-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb108-2" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 6
##   Commodity           Date       Unit  Minimum Maximum Average
##   &lt;chr&gt;               &lt;date&gt;     &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1 Tomato Big(Nepali)  2013-06-16 &lt;NA&gt;       35      40    37.5
## 2 Tomato Small(Local) 2013-06-16 &lt;NA&gt;       26      32    29  
## 3 Potato Red          2013-06-16 &lt;NA&gt;       20      21    20.5
## 4 Potato White        2013-06-16 &lt;NA&gt;       15      16    15.5
## 5 Onion Dry (Indian)  2013-06-16 &lt;NA&gt;       28      30    29  
## 6 Carrot(Local)       2013-06-16 &lt;NA&gt;       30      35    32.5</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb110-1" tabindex="-1"></a><span class="fu">str</span>(data)</span></code></pre></div>
<pre><code>## tibble [197,161 × 6] (S3: tbl_df/tbl/data.frame)
##  $ Commodity: chr [1:197161] &quot;Tomato Big(Nepali)&quot; &quot;Tomato Small(Local)&quot; &quot;Potato Red&quot; &quot;Potato White&quot; ...
##  $ Date     : Date[1:197161], format: &quot;2013-06-16&quot; &quot;2013-06-16&quot; ...
##  $ Unit     : chr [1:197161] NA NA NA NA ...
##  $ Minimum  : num [1:197161] 35 26 20 15 28 30 6 30 35 25 ...
##  $ Maximum  : num [1:197161] 40 32 21 16 30 35 10 35 40 30 ...
##  $ Average  : num [1:197161] 37.5 29 20.5 15.5 29 32.5 8 32.5 37.5 27.5 ...</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb112-1" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code></pre></div>
<pre><code>##   Commodity              Date                Unit              Minimum       
##  Length:197161      Min.   :2013-06-16   Length:197161      Min.   :   1.00  
##  Class :character   1st Qu.:2015-08-24   Class :character   1st Qu.:  40.00  
##  Mode  :character   Median :2017-08-03   Mode  :character   Median :  60.00  
##                     Mean   :2017-08-09                      Mean   :  85.42  
##                     3rd Qu.:2019-08-27                      3rd Qu.: 100.00  
##                     Max.   :2021-05-13                      Max.   :1800.00  
##     Maximum           Average       
##  Min.   :   6.00   Min.   :   5.00  
##  1st Qu.:  45.00   1st Qu.:  42.50  
##  Median :  70.00   Median :  65.00  
##  Mean   :  94.16   Mean   :  89.79  
##  3rd Qu.: 110.00   3rd Qu.: 105.00  
##  Max.   :2000.00   Max.   :1900.00</code></pre>
</div>
<div id="datos-nulos-y-duplicados" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> <strong>Datos nulos y duplicados</strong><a href="modelos-estacionales-en-series-de-tiempo.html#datos-nulos-y-duplicados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb114-1" tabindex="-1"></a><span class="co"># NAs y duplicados generales</span></span>
<span id="cb114-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb114-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span></code></pre></div>
<pre><code>## [1] 197161</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb116-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(data))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb118-1" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(ggplot2)) {</span>
<span id="cb118-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb118-2" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb118-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb118-3" tabindex="-1"></a>  <span class="fu">library</span>(ggplot2)</span>
<span id="cb118-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb118-4" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## Loading required package: ggplot2</code></pre>
</div>
<div id="análisis-univariado-1" class="section level3 hasAnchor" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> <strong>Análisis Univariado</strong><a href="modelos-estacionales-en-series-de-tiempo.html#análisis-univariado-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb120-1" tabindex="-1"></a><span class="co">#analisis univariado</span></span>
<span id="cb120-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb120-2" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Average)) <span class="sc">+</span></span>
<span id="cb120-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb120-3" tabindex="-1"></a><span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb120-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb120-4" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribucion de Precios Promedio&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Precio Promedio&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">+</span></span>
<span id="cb120-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb120-5" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb121-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb121-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb121-2" tabindex="-1"></a><span class="fu">summarise</span>(</span>
<span id="cb121-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb121-3" tabindex="-1"></a><span class="at">Mean =</span> <span class="fu">mean</span>(Average, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb121-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb121-4" tabindex="-1"></a><span class="at">Median =</span> <span class="fu">median</span>(Average, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb121-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb121-5" tabindex="-1"></a><span class="at">SD =</span> <span class="fu">sd</span>(Average, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb121-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb121-6" tabindex="-1"></a><span class="at">Min =</span> <span class="fu">min</span>(Average, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb121-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb121-7" tabindex="-1"></a><span class="at">Max =</span> <span class="fu">max</span>(Average, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb121-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb121-8" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##    Mean Median    SD   Min   Max
##   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  89.8     65  79.6     5  1900</code></pre>
</div>
<div id="análisis-bivariado-1" class="section level3 hasAnchor" number="4.1.5">
<h3><span class="header-section-number">4.1.5</span> <strong>Análisis Bivariado</strong><a href="modelos-estacionales-en-series-de-tiempo.html#análisis-bivariado-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb123-1" tabindex="-1"></a><span class="co">#analisis bivariado</span></span>
<span id="cb123-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb123-2" tabindex="-1"></a></span>
<span id="cb123-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb123-3" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Minimum, <span class="at">y =</span> Maximum)) <span class="sc">+</span></span>
<span id="cb123-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb123-4" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb123-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb123-5" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relacion entre Precio Minimo y Maximo&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Precio Minimo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Precio Maximo&quot;</span>) <span class="sc">+</span></span>
<span id="cb123-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb123-6" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb124-1" tabindex="-1"></a><span class="fu">cor</span>(data<span class="sc">$</span>Minimum, data<span class="sc">$</span>Maximum, <span class="at">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 0.9950614</code></pre>
</div>
</div>
<div id="analisis-de-series-de-tiempo-2" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> <strong>1.1 Analisis de series de tiempo</strong><a href="modelos-estacionales-en-series-de-tiempo.html#analisis-de-series-de-tiempo-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-1" tabindex="-1"></a><span class="cf">if</span> (<span class="st">&quot;Potato Red&quot;</span> <span class="sc">%in%</span> <span class="fu">unique</span>(data<span class="sc">$</span>Commodity)) {</span>
<span id="cb126-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-2" tabindex="-1"></a>target_item <span class="ot">&lt;-</span> <span class="st">&quot;Potato Red&quot;</span></span>
<span id="cb126-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb126-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-4" tabindex="-1"></a>target_item <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb126-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-5" tabindex="-1"></a><span class="fu">count</span>(Commodity, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb126-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-6" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb126-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-7" tabindex="-1"></a><span class="fu">pull</span>(Commodity)</span>
<span id="cb126-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-8" tabindex="-1"></a>}</span>
<span id="cb126-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-9" tabindex="-1"></a></span>
<span id="cb126-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb126-10" tabindex="-1"></a>target_item</span></code></pre></div>
<pre><code>## [1] &quot;Potato Red&quot;</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-1" tabindex="-1"></a><span class="co"># Filtrar y regularizar serie diaria</span></span>
<span id="cb128-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-2" tabindex="-1"></a></span>
<span id="cb128-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-3" tabindex="-1"></a>potatored <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb128-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-4" tabindex="-1"></a><span class="fu">filter</span>(Commodity <span class="sc">==</span> target_item) <span class="sc">%&gt;%</span></span>
<span id="cb128-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-5" tabindex="-1"></a><span class="fu">select</span>(Date, Average) <span class="sc">%&gt;%</span></span>
<span id="cb128-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-6" tabindex="-1"></a><span class="fu">group_by</span>(Date) <span class="sc">%&gt;%</span></span>
<span id="cb128-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-7" tabindex="-1"></a><span class="fu">summarise</span>(<span class="at">Average =</span> <span class="fu">mean</span>(Average), <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb128-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-8" tabindex="-1"></a><span class="fu">complete</span>(<span class="at">Date =</span> <span class="fu">seq</span>(<span class="fu">min</span>(Date, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">max</span>(Date, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">by =</span> <span class="st">&quot;day&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb128-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-9" tabindex="-1"></a><span class="fu">arrange</span>(Date)</span>
<span id="cb128-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-10" tabindex="-1"></a></span>
<span id="cb128-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-11" tabindex="-1"></a><span class="co"># Construir objeto ts (diario, 365)</span></span>
<span id="cb128-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-12" tabindex="-1"></a></span>
<span id="cb128-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-13" tabindex="-1"></a>pot_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(</span>
<span id="cb128-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-14" tabindex="-1"></a>potatored<span class="sc">$</span>Average,</span>
<span id="cb128-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-15" tabindex="-1"></a><span class="at">start =</span> <span class="fu">c</span>(lubridate<span class="sc">::</span><span class="fu">year</span>(<span class="fu">min</span>(potatored<span class="sc">$</span>Date, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb128-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-16" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">yday</span>(<span class="fu">min</span>(potatored<span class="sc">$</span>Date, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))),</span>
<span id="cb128-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-17" tabindex="-1"></a><span class="at">frequency =</span> <span class="dv">365</span></span>
<span id="cb128-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb128-18" tabindex="-1"></a>)</span></code></pre></div>
</div>
<div id="serie-basica-y-acf-2" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> <strong>1.2 Serie basica y ACF</strong><a href="modelos-estacionales-en-series-de-tiempo.html#serie-basica-y-acf-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-1" tabindex="-1"></a><span class="co"># --- Hotfix para error &quot;rstudio$.rs.isDesktop()&quot; ---</span></span>
<span id="cb129-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-2" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">&quot;rstudio&quot;</span>, <span class="at">envir =</span> .GlobalEnv)) <span class="fu">rm</span>(<span class="st">&quot;rstudio&quot;</span>, <span class="at">envir =</span> .GlobalEnv)</span>
<span id="cb129-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-3" tabindex="-1"></a><span class="fu">options</span>(<span class="at">device.ask.default =</span> <span class="cn">FALSE</span>)</span>
<span id="cb129-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-4" tabindex="-1"></a></span>
<span id="cb129-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-5" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">capabilities</span>(<span class="st">&quot;cairo&quot;</span>)) {</span>
<span id="cb129-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-6" tabindex="-1"></a>  knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev =</span> <span class="st">&quot;png&quot;</span>, <span class="at">dpi =</span> <span class="dv">150</span>, <span class="at">dev.args =</span> <span class="fu">list</span>(<span class="at">type =</span> <span class="st">&quot;cairo&quot;</span>))</span>
<span id="cb129-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-7" tabindex="-1"></a>  <span class="fu">options</span>(<span class="at">bitmapType =</span> <span class="st">&quot;cairo&quot;</span>)</span>
<span id="cb129-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-8" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb129-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-9" tabindex="-1"></a>  knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev =</span> <span class="st">&quot;png&quot;</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span>
<span id="cb129-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-10" tabindex="-1"></a>}</span>
<span id="cb129-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-11" tabindex="-1"></a></span>
<span id="cb129-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb129-12" tabindex="-1"></a><span class="fu">try</span>(<span class="fu">graphics.off</span>(), <span class="at">silent =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb130-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb130-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb130-2" tabindex="-1"></a><span class="fu">library</span>(forecast)</span></code></pre></div>
<pre><code>## Warning: package &#39;forecast&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-1" tabindex="-1"></a><span class="fu">autoplot</span>(pot_ts) <span class="sc">+</span></span>
<span id="cb132-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-2" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb132-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-3" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;📈 Serie de tiempo: precio promedio&quot;</span>,</span>
<span id="cb132-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-4" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Precio promedio&quot;</span>,</span>
<span id="cb132-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-5" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Tiempo&quot;</span></span>
<span id="cb132-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-6" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb132-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb132-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-8" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb132-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-9" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#2C3E50&quot;</span>, <span class="at">size =</span> <span class="dv">15</span>),</span>
<span id="cb132-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-10" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#34495E&quot;</span>),</span>
<span id="cb132-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-11" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb132-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-12" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;grey90&quot;</span>)</span>
<span id="cb132-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb132-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-9-1.png" width="1050" /></p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb133-1" tabindex="-1"></a><span class="fu">ggAcf</span>(pot_ts) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ACF del precio promedio (diario)&quot;</span>)</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-10-1.png" width="1050" /></p>
</div>
<div id="suavizamiento-temporal" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> <strong>2. Suavizamiento temporal</strong><a href="modelos-estacionales-en-series-de-tiempo.html#suavizamiento-temporal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Con el objetivo de aclarar la señal subyacente y separar ruido de corto plazo, se aplicaron promedios móviles (MA) de 7 y 30 días sobre la serie diaria de Average. El MA(7) capturó ciclos intra-semanales asociados a dinámica de mercado y logística, mientras que el MA(30) reveló una tendencia más estructural.</p>
<p>Interpretación. El patrón suavizado sugiere una tendencia suave al alza con episodios de fluctuación estacional. Este hallazgo justifica el uso posterior de modelos con componentes de tendencia y estacionalidad, y confirma la presencia de persistencia temporal (autocorrelación positiva en rezagos cortos), lo que anticipa buen desempeño de métodos como ARIMA/ETS.</p>
</div>
<div id="promedios-moviles-evidencia-de-suavizado-2" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> <strong>2.1 Promedios moviles (evidencia de suavizado)</strong><a href="modelos-estacionales-en-series-de-tiempo.html#promedios-moviles-evidencia-de-suavizado-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb134-1" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">&quot;rstudio&quot;</span>, <span class="at">envir =</span> .GlobalEnv)) <span class="fu">rm</span>(<span class="st">&quot;rstudio&quot;</span>, <span class="at">envir =</span> .GlobalEnv)</span>
<span id="cb134-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb134-2" tabindex="-1"></a><span class="fu">options</span>(<span class="at">device.ask.default =</span> <span class="cn">FALSE</span>)</span>
<span id="cb134-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb134-3" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">capabilities</span>(<span class="st">&quot;cairo&quot;</span>)) {</span>
<span id="cb134-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb134-4" tabindex="-1"></a>  knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev =</span> <span class="st">&quot;png&quot;</span>, <span class="at">dpi =</span> <span class="dv">150</span>, <span class="at">dev.args =</span> <span class="fu">list</span>(<span class="at">type =</span> <span class="st">&quot;cairo&quot;</span>))</span>
<span id="cb134-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb134-5" tabindex="-1"></a>  <span class="fu">options</span>(<span class="at">bitmapType =</span> <span class="st">&quot;cairo&quot;</span>)</span>
<span id="cb134-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb134-6" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb134-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb134-7" tabindex="-1"></a>  knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev =</span> <span class="st">&quot;png&quot;</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span>
<span id="cb134-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb134-8" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-1" tabindex="-1"></a><span class="co"># Hotfix global para gráficos (evita el viewer de RStudio)</span></span>
<span id="cb135-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-2" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">&quot;rstudio&quot;</span>, <span class="at">envir =</span> .GlobalEnv)) <span class="fu">rm</span>(<span class="st">&quot;rstudio&quot;</span>, <span class="at">envir =</span> .GlobalEnv)</span>
<span id="cb135-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-3" tabindex="-1"></a><span class="fu">options</span>(<span class="at">device.ask.default =</span> <span class="cn">FALSE</span>)</span>
<span id="cb135-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-4" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">capabilities</span>(<span class="st">&quot;cairo&quot;</span>)) {</span>
<span id="cb135-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-5" tabindex="-1"></a>  knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev =</span> <span class="st">&quot;png&quot;</span>, <span class="at">dpi =</span> <span class="dv">150</span>, <span class="at">dev.args =</span> <span class="fu">list</span>(<span class="at">type =</span> <span class="st">&quot;cairo&quot;</span>))</span>
<span id="cb135-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-6" tabindex="-1"></a>  <span class="fu">options</span>(<span class="at">bitmapType =</span> <span class="st">&quot;cairo&quot;</span>)</span>
<span id="cb135-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-7" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb135-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-8" tabindex="-1"></a>  knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev =</span> <span class="st">&quot;png&quot;</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span>
<span id="cb135-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb135-9" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-1" tabindex="-1"></a><span class="co"># --- Hotfix global: NO viewer, render a PNG ---</span></span>
<span id="cb136-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-2" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">&quot;rstudio&quot;</span>, <span class="at">envir =</span> .GlobalEnv)) <span class="fu">rm</span>(<span class="st">&quot;rstudio&quot;</span>, <span class="at">envir =</span> .GlobalEnv)</span>
<span id="cb136-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-3" tabindex="-1"></a><span class="fu">options</span>(<span class="at">device.ask.default =</span> <span class="cn">FALSE</span>)</span>
<span id="cb136-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-4" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">capabilities</span>(<span class="st">&quot;cairo&quot;</span>)) {</span>
<span id="cb136-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-5" tabindex="-1"></a>  knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev =</span> <span class="st">&quot;png&quot;</span>, <span class="at">dpi =</span> <span class="dv">150</span>, <span class="at">dev.args =</span> <span class="fu">list</span>(<span class="at">type =</span> <span class="st">&quot;cairo&quot;</span>))</span>
<span id="cb136-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-6" tabindex="-1"></a>  <span class="fu">options</span>(<span class="at">bitmapType =</span> <span class="st">&quot;cairo&quot;</span>)</span>
<span id="cb136-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-7" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb136-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-8" tabindex="-1"></a>  knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev =</span> <span class="st">&quot;png&quot;</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span>
<span id="cb136-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-9" tabindex="-1"></a>}</span>
<span id="cb136-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-10" tabindex="-1"></a></span>
<span id="cb136-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-11" tabindex="-1"></a><span class="co"># Paquetes mínimos</span></span>
<span id="cb136-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-12" tabindex="-1"></a>libs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;dplyr&quot;</span>,<span class="st">&quot;tidyr&quot;</span>,<span class="st">&quot;lubridate&quot;</span>,<span class="st">&quot;slider&quot;</span>)</span>
<span id="cb136-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb136-13" tabindex="-1"></a><span class="cf">for</span> (p <span class="cf">in</span> libs) <span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(p, <span class="at">character.only=</span><span class="cn">TRUE</span>)) {<span class="fu">install.packages</span>(p); <span class="fu">library</span>(p, <span class="at">character.only=</span><span class="cn">TRUE</span>)}</span></code></pre></div>
<pre><code>## Loading required package: slider</code></pre>
<pre><code>## Warning: package &#39;slider&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb139-1" tabindex="-1"></a><span class="co"># Utilidad para guardar junto al Rmd</span></span>
<span id="cb139-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb139-2" tabindex="-1"></a>safe_dir <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb139-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb139-3" tabindex="-1"></a>  f <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(knitr<span class="sc">::</span><span class="fu">current_input</span>(), <span class="at">error=</span><span class="cf">function</span>(e) <span class="cn">NULL</span>)</span>
<span id="cb139-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb139-4" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(f) <span class="sc">&amp;&amp;</span> <span class="fu">nzchar</span>(f)) <span class="fu">dirname</span>(<span class="fu">normalizePath</span>(f)) <span class="cf">else</span> <span class="fu">getwd</span>()</span>
<span id="cb139-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb139-5" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="promedios-móviles-7-y-30-base-r-png-include" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> <strong>2.2 Promedios móviles (7 y 30) — Base R + PNG + include</strong><a href="modelos-estacionales-en-series-de-tiempo.html#promedios-móviles-7-y-30-base-r-png-include" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-1" tabindex="-1"></a><span class="co"># Librerías necesarias</span></span>
<span id="cb140-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-2" tabindex="-1"></a></span>
<span id="cb140-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb140-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-4" tabindex="-1"></a><span class="fu">library</span>(slider)</span>
<span id="cb140-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-5" tabindex="-1"></a></span>
<span id="cb140-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-6" tabindex="-1"></a><span class="co"># Calcular promedios móviles</span></span>
<span id="cb140-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-7" tabindex="-1"></a></span>
<span id="cb140-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-8" tabindex="-1"></a>pot_ma <span class="ot">&lt;-</span> potatored</span>
<span id="cb140-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-9" tabindex="-1"></a>pot_ma<span class="sc">$</span>ma7  <span class="ot">&lt;-</span> <span class="fu">slide_dbl</span>(pot_ma<span class="sc">$</span>Average, mean, <span class="at">.before =</span> <span class="dv">6</span>,  <span class="at">.complete =</span> <span class="cn">TRUE</span>)</span>
<span id="cb140-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-10" tabindex="-1"></a>pot_ma<span class="sc">$</span>ma30 <span class="ot">&lt;-</span> <span class="fu">slide_dbl</span>(pot_ma<span class="sc">$</span>Average, mean, <span class="at">.before =</span> <span class="dv">29</span>, <span class="at">.complete =</span> <span class="cn">TRUE</span>)</span>
<span id="cb140-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-11" tabindex="-1"></a></span>
<span id="cb140-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-12" tabindex="-1"></a><span class="co"># Gráfico con ggplot2</span></span>
<span id="cb140-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-13" tabindex="-1"></a></span>
<span id="cb140-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-14" tabindex="-1"></a><span class="fu">ggplot</span>(pot_ma, <span class="fu">aes</span>(<span class="at">x =</span> Date)) <span class="sc">+</span></span>
<span id="cb140-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-15" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Average, <span class="at">color =</span> <span class="st">&quot;Serie original&quot;</span>), <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb140-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-16" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> ma7,  <span class="at">color =</span> <span class="st">&quot;Media móvil 7 días&quot;</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb140-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-17" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> ma30, <span class="at">color =</span> <span class="st">&quot;Media móvil 30 días&quot;</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb140-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-18" tabindex="-1"></a><span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Serie original&quot;</span><span class="ot">=</span><span class="st">&quot;#1F77B4&quot;</span>,</span>
<span id="cb140-19"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-19" tabindex="-1"></a><span class="st">&quot;Media móvil 7 días&quot;</span><span class="ot">=</span><span class="st">&quot;#FF7F0E&quot;</span>,</span>
<span id="cb140-20"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-20" tabindex="-1"></a><span class="st">&quot;Media móvil 30 días&quot;</span><span class="ot">=</span><span class="st">&quot;#2CA02C&quot;</span>)) <span class="sc">+</span></span>
<span id="cb140-21"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-21" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Serie y promedios móviles (7 y 30 días)&quot;</span>,</span>
<span id="cb140-22"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-22" tabindex="-1"></a><span class="at">x =</span> <span class="st">&quot;Fecha&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Precio promedio&quot;</span>, <span class="at">color =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-23"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-23" tabindex="-1"></a><span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb140-24"><a href="modelos-estacionales-en-series-de-tiempo.html#cb140-24" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;top&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 118 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 407 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<p><img src="04-application_files/figure-html/unnamed-chunk-14-1.png" width="1050" /></p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-1" tabindex="-1"></a><span class="co"># Librerías necesarias</span></span>
<span id="cb143-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-2" tabindex="-1"></a></span>
<span id="cb143-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb143-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-4" tabindex="-1"></a><span class="fu">library</span>(slider)</span>
<span id="cb143-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-5" tabindex="-1"></a></span>
<span id="cb143-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-6" tabindex="-1"></a><span class="co"># Calcular promedios móviles</span></span>
<span id="cb143-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-7" tabindex="-1"></a></span>
<span id="cb143-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-8" tabindex="-1"></a>pot_ma <span class="ot">&lt;-</span> potatored</span>
<span id="cb143-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-9" tabindex="-1"></a>pot_ma<span class="sc">$</span>ma7  <span class="ot">&lt;-</span> <span class="fu">slide_dbl</span>(pot_ma<span class="sc">$</span>Average, mean, <span class="at">.before =</span> <span class="dv">6</span>,  <span class="at">.complete =</span> <span class="cn">TRUE</span>)</span>
<span id="cb143-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-10" tabindex="-1"></a>pot_ma<span class="sc">$</span>ma30 <span class="ot">&lt;-</span> <span class="fu">slide_dbl</span>(pot_ma<span class="sc">$</span>Average, mean, <span class="at">.before =</span> <span class="dv">29</span>, <span class="at">.complete =</span> <span class="cn">TRUE</span>)</span>
<span id="cb143-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-11" tabindex="-1"></a></span>
<span id="cb143-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-12" tabindex="-1"></a><span class="co"># Gráfico con ggplot2</span></span>
<span id="cb143-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-13" tabindex="-1"></a></span>
<span id="cb143-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-14" tabindex="-1"></a><span class="fu">ggplot</span>(pot_ma, <span class="fu">aes</span>(<span class="at">x =</span> Date)) <span class="sc">+</span></span>
<span id="cb143-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-15" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Average, <span class="at">color =</span> <span class="st">&quot;Serie original&quot;</span>), <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb143-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-16" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> ma7,  <span class="at">color =</span> <span class="st">&quot;Media móvil 7 días&quot;</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb143-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-17" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> ma30, <span class="at">color =</span> <span class="st">&quot;Media móvil 30 días&quot;</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb143-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-18" tabindex="-1"></a><span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Serie original&quot;</span><span class="ot">=</span><span class="st">&quot;#1F77B4&quot;</span>,</span>
<span id="cb143-19"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-19" tabindex="-1"></a><span class="st">&quot;Media móvil 7 días&quot;</span><span class="ot">=</span><span class="st">&quot;#FF7F0E&quot;</span>,</span>
<span id="cb143-20"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-20" tabindex="-1"></a><span class="st">&quot;Media móvil 30 días&quot;</span><span class="ot">=</span><span class="st">&quot;#2CA02C&quot;</span>)) <span class="sc">+</span></span>
<span id="cb143-21"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-21" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Serie y promedios móviles (7 y 30 días)&quot;</span>,</span>
<span id="cb143-22"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-22" tabindex="-1"></a><span class="at">x =</span> <span class="st">&quot;Fecha&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Precio promedio&quot;</span>, <span class="at">color =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb143-23"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-23" tabindex="-1"></a><span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb143-24"><a href="modelos-estacionales-en-series-de-tiempo.html#cb143-24" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;top&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 118 rows containing missing values or values outside the scale range
## (`geom_line()`).
## Removed 407 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<p><img src="04-application_files/figure-html/unnamed-chunk-14-2.png" width="1050" /></p>
</div>
<div id="serie-básica-ts-base-r-png-include" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> <strong>2.3 Serie básica (ts) — Base R + PNG + include</strong><a href="modelos-estacionales-en-series-de-tiempo.html#serie-básica-ts-base-r-png-include" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb145-1" tabindex="-1"></a><span class="co"># Gráfico base de la serie</span></span>
<span id="cb145-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb145-2" tabindex="-1"></a></span>
<span id="cb145-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb145-3" tabindex="-1"></a><span class="fu">ggplot</span>(potatored, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Average)) <span class="sc">+</span></span>
<span id="cb145-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb145-4" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;#1F77B4&quot;</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb145-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb145-5" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Serie de tiempo: precio promedio&quot;</span>,</span>
<span id="cb145-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb145-6" tabindex="-1"></a><span class="at">x =</span> <span class="st">&quot;Fecha&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Precio promedio&quot;</span>) <span class="sc">+</span></span>
<span id="cb145-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb145-7" tabindex="-1"></a><span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>)</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-15-1.png" width="1050" /></p>
</div>
<div id="rezagos-lags-y-dependencia-temporal-2" class="section level2 hasAnchor" number="4.8">
<h2><span class="header-section-number">4.8</span> <strong>2.4 Rezagos (lags) y dependencia temporal</strong><a href="modelos-estacionales-en-series-de-tiempo.html#rezagos-lags-y-dependencia-temporal-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-1" tabindex="-1"></a>pot_lags <span class="ot">&lt;-</span> potatored <span class="sc">%&gt;%</span></span>
<span id="cb146-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb146-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-3" tabindex="-1"></a>    <span class="at">lag1  =</span> dplyr<span class="sc">::</span><span class="fu">lag</span>(Average, <span class="dv">1</span>),</span>
<span id="cb146-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-4" tabindex="-1"></a>    <span class="at">lag7  =</span> dplyr<span class="sc">::</span><span class="fu">lag</span>(Average, <span class="dv">7</span>),</span>
<span id="cb146-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-5" tabindex="-1"></a>    <span class="at">lag30 =</span> dplyr<span class="sc">::</span><span class="fu">lag</span>(Average, <span class="dv">30</span>)</span>
<span id="cb146-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-6" tabindex="-1"></a>  )</span>
<span id="cb146-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-7" tabindex="-1"></a></span>
<span id="cb146-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-8" tabindex="-1"></a><span class="co"># Scatter y_t vs y_{t-1}</span></span>
<span id="cb146-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-9" tabindex="-1"></a><span class="fu">ggplot</span>(pot_lags, <span class="fu">aes</span>(lag1, Average)) <span class="sc">+</span></span>
<span id="cb146-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-10" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb146-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-11" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb146-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb146-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb146-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Scatter rezago 1 (y_t vs y_{t-1})&quot;</span>, <span class="at">x =</span> <span class="st">&quot;y_{t-1}&quot;</span>, <span class="at">y =</span> <span class="st">&quot;y_t&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 251 rows containing non-finite outside the scale range
## (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 251 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="04-application_files/figure-html/unnamed-chunk-16-1.png" width="1050" /></p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb150-1" tabindex="-1"></a><span class="co"># Scatter y_t vs y_{t-7}</span></span>
<span id="cb150-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb150-2" tabindex="-1"></a><span class="fu">ggplot</span>(pot_lags, <span class="fu">aes</span>(lag7, Average)) <span class="sc">+</span></span>
<span id="cb150-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb150-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb150-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb150-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb150-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb150-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb150-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb150-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Scatter rezago 7 (aprox. semanal)&quot;</span>, <span class="at">x =</span> <span class="st">&quot;y_{t-7}&quot;</span>, <span class="at">y =</span> <span class="st">&quot;y_t&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 234 rows containing non-finite outside the scale range
## (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 234 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="04-application_files/figure-html/unnamed-chunk-16-2.png" width="1050" /></p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb154-1" tabindex="-1"></a><span class="co"># ACF/PACF (serie regularizada)</span></span>
<span id="cb154-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb154-2" tabindex="-1"></a><span class="fu">ggAcf</span>(pot_ts)  <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ACF precio promedio (diario)&quot;</span>)</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-16-3.png" width="1050" /></p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb155-1" tabindex="-1"></a><span class="fu">ggPacf</span>(pot_ts) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;PACF precio promedio (diario)&quot;</span>)</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-16-4.png" width="1050" /></p>
</div>
<div id="estacionalidad-descomposicion-stl-2" class="section level2 hasAnchor" number="4.9">
<h2><span class="header-section-number">4.9</span> <strong>2.5 Estacionalidad (descomposicion STL)</strong><a href="modelos-estacionales-en-series-de-tiempo.html#estacionalidad-descomposicion-stl-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb156-1" tabindex="-1"></a>fit_stl <span class="ot">&lt;-</span> <span class="fu">stl</span>(<span class="fu">na.interp</span>(pot_ts), <span class="at">s.window =</span> <span class="st">&quot;periodic&quot;</span>, <span class="at">robust =</span> <span class="cn">TRUE</span>)</span>
<span id="cb156-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb156-2" tabindex="-1"></a><span class="fu">autoplot</span>(fit_stl) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;STL precio promedio&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## ℹ The deprecated feature was likely used in the forecast package.
##   Please report the issue at &lt;https://github.com/robjhyndman/forecast/issues&gt;.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<p><img src="04-application_files/figure-html/unnamed-chunk-17-1.png" width="1050" />
El análisis de la serie temporal del precio promedio diario de Potato Red permitió evidenciar comportamientos consistentes con los fenómenos propios de los productos agrícolas de consumo masivo.
En primer lugar, los gráficos de tendencia y promedios móviles muestran que los precios presentan fluctuaciones periódicas pero con una ligera tendencia creciente en el largo plazo. El promedio móvil de 7 días suaviza las variaciones diarias y deja entrever ciclos semanales asociados a la oferta en el mercado, mientras que el promedio de 30 días resalta un patrón más estructural que apunta a incrementos graduales, posiblemente relacionados con factores estacionales como la disponibilidad de cosecha o la variación de costos logísticos.</p>
<p>El estudio de rezagos (lag 1, lag 7 y lag 30) refuerza esta observación: las gráficas de dispersión muestran una clara autocorrelación positiva, especialmente para rezagos cortos, indicando que los precios actuales dependen directamente de los valores recientes. Este comportamiento sugiere persistencia temporal: cuando los precios aumentan o disminuyen, tienden a mantener esa dirección durante varios días, lo cual es característico de mercados donde la información y las condiciones de oferta no cambian abruptamente.</p>
<p>La función de autocorrelación (ACF) confirma esta dependencia temporal, con correlaciones significativas en los primeros rezagos que luego disminuyen de forma progresiva. Esto demuestra que la serie no sigue un comportamiento completamente aleatorio, sino que existen patrones repetitivos en el tiempo.</p>
<p>La descomposición STL separó la serie en sus componentes de tendencia, estacionalidad y residuo. Los resultados muestran una estacionalidad marcada con ciclos anuales definidos: los precios tienden a elevarse en ciertas épocas del año y disminuir en otras, reflejando los periodos de cosecha y escasez. La tendencia general es estable con una leve inclinación al alza, mientras que los residuos mantienen una magnitud baja y no presentan patrones visibles, lo que indica que gran parte de la variabilidad del precio está explicada por la tendencia y la estacionalidad, sin presencia de choques exógenos significativos.</p>
<p>En conjunto, estos hallazgos evidencian que la serie del precio promedio de Potato Red posee un comportamiento no estacionario, con una tendencia creciente y estacionalidad recurrente, pero sin irregularidades fuertes.
El patrón identificado sugiere que los precios pueden modelarse de forma confiable mediante técnicas de suavizado exponencial o modelos ARIMA estacionales, una vez que se realicen las transformaciones necesarias para estabilizar la media y la varianza. En términos prácticos, los resultados reflejan que el mercado analizado responde a ciclos previsibles, lo cual facilita la planificación de precios, abastecimiento y estrategias de comercialización.</p>
</div>
<div id="estacionariedad-y-diferenciación-2" class="section level2 hasAnchor" number="4.10">
<h2><span class="header-section-number">4.10</span> <strong>Estacionariedad y diferenciación</strong><a href="modelos-estacionales-en-series-de-tiempo.html#estacionariedad-y-diferenciación-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Introducción
En esta segunda parte se busca analizar si la serie de tiempo seleccionada (Potato Red) cumple con el supuesto de estacionariedad. Una serie estacionaria es aquella cuya media y varianza permanecen constantes en el tiempo.
En caso de que no sea estacionaria, se aplicarán procedimientos de diferenciación # o transformación para estabilizar la tendencia y la variabilidad.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-1" tabindex="-1"></a><span class="co"># Usaremos una version &quot;limpia&quot; de la serie via interpolacion lineal base R, partimos de &#39;potatored&#39; (data.frame terminado) y/o de &#39;pot_ts&#39; (ts original)</span></span>
<span id="cb158-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-2" tabindex="-1"></a></span>
<span id="cb158-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-3" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(pot_ts)</span>
<span id="cb158-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-4" tabindex="-1"></a></span>
<span id="cb158-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-5" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">anyNA</span>(y)) {</span>
<span id="cb158-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-6" tabindex="-1"></a>  idx_ok <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="sc">!</span><span class="fu">is.na</span>(y))</span>
<span id="cb158-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-7" tabindex="-1"></a>  y_interp <span class="ot">&lt;-</span> <span class="fu">approx</span>(<span class="at">x =</span> idx_ok, <span class="at">y =</span> y[idx_ok], <span class="at">xout =</span> <span class="fu">seq_along</span>(y))<span class="sc">$</span>y</span>
<span id="cb158-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-8" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb158-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-9" tabindex="-1"></a>  y_interp <span class="ot">&lt;-</span> y}</span>
<span id="cb158-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-10" tabindex="-1"></a></span>
<span id="cb158-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-11" tabindex="-1"></a></span>
<span id="cb158-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-12" tabindex="-1"></a>pot_ts_clean <span class="ot">&lt;-</span> <span class="fu">ts</span>(</span>
<span id="cb158-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-13" tabindex="-1"></a>  y_interp,</span>
<span id="cb158-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-14" tabindex="-1"></a>  <span class="at">start =</span> <span class="fu">start</span>(pot_ts),</span>
<span id="cb158-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-15" tabindex="-1"></a>  <span class="at">frequency =</span> <span class="fu">frequency</span>(pot_ts)</span>
<span id="cb158-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb158-16" tabindex="-1"></a>)</span></code></pre></div>
</div>
<div id="verificación-de-estacionariedad-adf-test-2" class="section level2 hasAnchor" number="4.11">
<h2><span class="header-section-number">4.11</span> <strong>Verificación de estacionariedad (ADF Test)</strong><a href="modelos-estacionales-en-series-de-tiempo.html#verificación-de-estacionariedad-adf-test-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb159-1" tabindex="-1"></a><span class="co"># Prueba de raíz unitaria de Dickey-Fuller aumentada</span></span>
<span id="cb159-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb159-2" tabindex="-1"></a></span>
<span id="cb159-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb159-3" tabindex="-1"></a>adf_result <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(pot_ts_clean)</span>
<span id="cb159-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb159-4" tabindex="-1"></a>adf_result</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  pot_ts_clean
## Dickey-Fuller = -3.0587, Lag order = 14, p-value = 0.1301
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb161-1" tabindex="-1"></a><span class="co"># al tener en el ADF inicial: p = 0.1301 → se concluye que es no estacionaria al nive, por lo cual procedemos con transformacion y diferenciacion en escalones</span></span>
<span id="cb161-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb161-2" tabindex="-1"></a></span>
<span id="cb161-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb161-3" tabindex="-1"></a></span>
<span id="cb161-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb161-4" tabindex="-1"></a><span class="co"># Serie base a usar en esta etapa y verificamos que no tenga na ni valores negativos</span></span>
<span id="cb161-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb161-5" tabindex="-1"></a>y0 <span class="ot">&lt;-</span> pot_ts_clean </span>
<span id="cb161-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb161-6" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(y0))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb163-1" tabindex="-1"></a><span class="fu">all</span>(y0<span class="sc">&gt;</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb165-1" tabindex="-1"></a>y_log <span class="ot">&lt;-</span> <span class="fu">log</span>(y0)</span>
<span id="cb165-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb165-2" tabindex="-1"></a><span class="fu">range</span>(y0, <span class="at">na.rm =</span> <span class="cn">TRUE</span>); <span class="fu">range</span>(y_log, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  <span class="co"># solo para verificar el cambio de escala</span></span></code></pre></div>
<pre><code>## [1]  15.0 113.5</code></pre>
<pre><code>## [1] 2.708050 4.731803</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb168-1" tabindex="-1"></a>adf_log <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(y_log)</span>
<span id="cb168-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb168-2" tabindex="-1"></a>adf_log<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.1322035</code></pre>
<p>La transformación logarítmica ayudó a homogeneizar la variabilidad, pero no eliminó la tendencia ni la dependencia temporal. La serie transformada sigue teniendo raíz unitaria, por lo que pasamos a una diferenciacion de primer orden (d=1) sobre la serie logaritmica y volvemos a probar estacionariedad.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb170-1" tabindex="-1"></a>y_diff1 <span class="ot">&lt;-</span> <span class="fu">diff</span>(y_log, <span class="at">differences =</span> <span class="dv">1</span>)</span>
<span id="cb170-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb170-2" tabindex="-1"></a>adf_diff1 <span class="ot">&lt;-</span> tseries<span class="sc">::</span><span class="fu">adf.test</span>(<span class="fu">na.omit</span>(y_diff1))</span></code></pre></div>
<pre><code>## Warning in tseries::adf.test(na.omit(y_diff1)): p-value smaller than printed
## p-value</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb172-1" tabindex="-1"></a>adf_diff1<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.01</code></pre>
<p>con este resultado podemos concluir que:</p>
<ul>
<li><p>La serie original no era estacionaria (p = 0.1301).</p></li>
<li><p>La serie logarítmica tampoco lo fue (p = 0.1322), aunque esa transformación ayudó a estabilizar la varianza</p></li>
<li><p>Al aplicar una diferencia de primer orden sobre la serie logarítmica, la prueba ADF arrojó p = 0.01, es decir &lt; 0.05, por lo tanto sí es estacionaria.</p></li>
</ul>
</div>
<div id="interpretacion-2" class="section level2 hasAnchor" number="4.12">
<h2><span class="header-section-number">4.12</span> <strong>Interpretacion</strong><a href="modelos-estacionales-en-series-de-tiempo.html#interpretacion-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Luego de aplicar la transformación logarítmica, la serie mantuvo la misma tendencia general, por lo que no se logró estacionariedad. Sin embargo, al diferenciarla una vez (d = 1), la prueba de Dickey–Fuller aumentada mostró un p-valor de 0.01, lo que indica que se rechaza la hipótesis nula de raíz unitaria. En consecuencia, la serie diferenciada es estacionaria.</p>
<p>Este resultado implica que la tendencia determinista fue eliminada mediante la primera diferencia, estabilizando la media a lo largo del tiempo. Por otro lado, la transformación logarítmica permitió controlar la heterocedasticidad, de modo que las fluctuaciones de la serie ahora son de magnitud comparable. La combinación de ambos pasos —logaritmo y diferencia de primer orden— produce una serie adecuada para modelar mediante métodos lineales, como los modelos ARIMA o SARIMA.</p>
<p>Visualmente, la serie diferenciada oscila alrededor de cero y las funciones de autocorrelación (ACF y PACF) se estabilizan rápidamente, lo que refuerza la evidencia de estacionariedad.</p>
</div>
<div id="ajuste-del-modelo-arima" class="section level2 hasAnchor" number="4.13">
<h2><span class="header-section-number">4.13</span> <strong>3. AJUSTE DEL MODELO ARIMA</strong><a href="modelos-estacionales-en-series-de-tiempo.html#ajuste-del-modelo-arima" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para seleccionar una especificación parsimoniosa se utilizó auto.arima(), que explora combinaciones de órdenes
(𝑝,𝑑,𝑞)
(p,d,q) y, cuando corresponde,
(𝑃,𝐷,𝑄)
(P,D,Q) estacionales, minimizando criterios de información como AIC (Akaike Information Criterion) y BIC (Bayesian Information Criterion).
Previo al ajuste se evaluó la estacionariedad (prueba ADF), aplicando transformación logarítmica para estabilizar varianza y diferenciación de primer orden para remover tendencia cuando fue necesario.</p>
</div>
<div id="criterios-de-selección" class="section level2 hasAnchor" number="4.14">
<h2><span class="header-section-number">4.14</span> <strong>3.1 Criterios de selección</strong><a href="modelos-estacionales-en-series-de-tiempo.html#criterios-de-selección" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>AIC penaliza menos la complejidad; útil para captar estructura.</p>
<p>BIC penaliza más; favorece modelos más simples.
Se eligió el modelo con AIC/BIC mínimos y residuos con comportamiento de ruido blanco.</p>
</div>
<div id="suavizamiento-y-holt-winters-sobre-la-variable-tiempo-1" class="section level2 hasAnchor" number="4.15">
<h2><span class="header-section-number">4.15</span> <strong>3.2 Suavizamiento y Holt-Winters sobre la variable tiempo</strong><a href="modelos-estacionales-en-series-de-tiempo.html#suavizamiento-y-holt-winters-sobre-la-variable-tiempo-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb174-1" tabindex="-1"></a>y_hw <span class="ot">&lt;-</span> <span class="fu">na.interp</span>(pot_ts) </span>
<span id="cb174-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb174-2" tabindex="-1"></a>freq <span class="ot">&lt;-</span> <span class="fu">frequency</span>(y_hw)   </span>
<span id="cb174-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb174-3" tabindex="-1"></a><span class="fu">length</span>(y_hw); freq</span></code></pre></div>
<pre><code>## [1] 2889</code></pre>
<pre><code>## [1] 365</code></pre>
</div>
<div id="particion-de-entrenamiento-prueba-1" class="section level2 hasAnchor" number="4.16">
<h2><span class="header-section-number">4.16</span> <strong>Particion de entrenamiento /prueba</strong><a href="modelos-estacionales-en-series-de-tiempo.html#particion-de-entrenamiento-prueba-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-1" tabindex="-1"></a>h_test <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="dv">365</span>, <span class="fu">floor</span>(<span class="fu">length</span>(y_hw)<span class="sc">*</span><span class="fl">0.2</span>))  <span class="co"># 1 año o ~20% si no alcanza</span></span>
<span id="cb177-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(y_hw)</span>
<span id="cb177-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-3" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> <span class="fu">window</span>(y_hw, <span class="at">end =</span> <span class="fu">time</span>(y_hw)[n <span class="sc">-</span> h_test])</span>
<span id="cb177-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-4" tabindex="-1"></a>y_test  <span class="ot">&lt;-</span> <span class="fu">window</span>(y_hw, <span class="at">start =</span> <span class="fu">time</span>(y_hw)[n <span class="sc">-</span> h_test <span class="sc">+</span> <span class="dv">1</span>])</span>
<span id="cb177-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-5" tabindex="-1"></a></span>
<span id="cb177-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-6" tabindex="-1"></a><span class="fu">autoplot</span>(y_hw) <span class="sc">+</span></span>
<span id="cb177-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-7" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">time</span>(y_hw)[n <span class="sc">-</span> h_test <span class="sc">+</span> <span class="dv">1</span>], <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb177-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Serie completa con corte train/test&quot;</span>,</span>
<span id="cb177-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Precio promedio&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Tiempo&quot;</span>) <span class="sc">+</span></span>
<span id="cb177-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb177-10" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-24-1.png" width="1050" />
## <strong>Agregación semanal</strong></p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb178-1" tabindex="-1"></a><span class="fu">library</span>(zoo)</span></code></pre></div>
<pre><code>## Warning: package &#39;zoo&#39; was built under R version 4.3.3</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-1" tabindex="-1"></a><span class="co"># y_hw: serie ts diaria (freq=365)</span></span>
<span id="cb182-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-2" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">frequency</span>(y_hw) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">365</span>, <span class="dv">366</span>))</span>
<span id="cb182-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-3" tabindex="-1"></a></span>
<span id="cb182-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-4" tabindex="-1"></a><span class="co">#secuencia de fechas real para la ts diaria</span></span>
<span id="cb182-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-5" tabindex="-1"></a>tsp_hw <span class="ot">&lt;-</span> <span class="fu">tsp</span>(y_hw)                     <span class="co"># c(start, end, freq)</span></span>
<span id="cb182-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-6" tabindex="-1"></a>start_year <span class="ot">&lt;-</span> <span class="fu">floor</span>(tsp_hw[<span class="dv">1</span>])</span>
<span id="cb182-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-7" tabindex="-1"></a>start_frac <span class="ot">&lt;-</span> tsp_hw[<span class="dv">1</span>] <span class="sc">-</span> start_year</span>
<span id="cb182-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-8" tabindex="-1"></a>start_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">paste0</span>(start_year, <span class="st">&quot;-01-01&quot;</span>)) <span class="sc">+</span> <span class="fu">round</span>(start_frac <span class="sc">*</span> <span class="fl">365.25</span>)</span>
<span id="cb182-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-9" tabindex="-1"></a></span>
<span id="cb182-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-10" tabindex="-1"></a>fechas_all <span class="ot">&lt;-</span> <span class="fu">seq.Date</span>(<span class="at">from =</span> start_date, <span class="at">by =</span> <span class="st">&quot;day&quot;</span>, <span class="at">length.out =</span> <span class="fu">length</span>(y_hw))</span>
<span id="cb182-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-11" tabindex="-1"></a>z_all <span class="ot">&lt;-</span> <span class="fu">zoo</span>(<span class="fu">as.numeric</span>(y_hw), fechas_all)</span>
<span id="cb182-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-12" tabindex="-1"></a></span>
<span id="cb182-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-13" tabindex="-1"></a><span class="co">#Agregar por semana calendario</span></span>
<span id="cb182-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-14" tabindex="-1"></a>z_week <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(z_all, <span class="fu">as.Date</span>(<span class="fu">cut</span>(<span class="fu">index</span>(z_all), <span class="st">&quot;week&quot;</span>)), mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb182-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-15" tabindex="-1"></a></span>
<span id="cb182-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-16" tabindex="-1"></a><span class="co">#Convertimos a ts semanal (freq = 52)</span></span>
<span id="cb182-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-17" tabindex="-1"></a>y_w <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">as.numeric</span>(z_week), <span class="at">frequency =</span> <span class="dv">52</span>)</span>
<span id="cb182-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-18" tabindex="-1"></a></span>
<span id="cb182-19"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-19" tabindex="-1"></a><span class="co">#Split train/test semanal</span></span>
<span id="cb182-20"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-20" tabindex="-1"></a>h_test_w <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="dv">52</span>, <span class="fu">floor</span>(<span class="fu">length</span>(y_w) <span class="sc">*</span> <span class="fl">0.2</span>))</span>
<span id="cb182-21"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-21" tabindex="-1"></a>n_w <span class="ot">&lt;-</span> <span class="fu">length</span>(y_w)</span>
<span id="cb182-22"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-22" tabindex="-1"></a>y_train_w <span class="ot">&lt;-</span> <span class="fu">window</span>(y_w, <span class="at">end =</span> <span class="fu">time</span>(y_w)[n_w <span class="sc">-</span> h_test_w])</span>
<span id="cb182-23"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-23" tabindex="-1"></a>y_test_w  <span class="ot">&lt;-</span> <span class="fu">window</span>(y_w, <span class="at">start =</span> <span class="fu">time</span>(y_w)[n_w <span class="sc">-</span> h_test_w <span class="sc">+</span> <span class="dv">1</span>])</span>
<span id="cb182-24"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-24" tabindex="-1"></a></span>
<span id="cb182-25"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-25" tabindex="-1"></a><span class="fu">autoplot</span>(y_w) <span class="sc">+</span></span>
<span id="cb182-26"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-26" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">time</span>(y_w)[n_w <span class="sc">-</span> h_test_w <span class="sc">+</span> <span class="dv">1</span>], <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb182-27"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-27" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Serie semanal con corte train/test&quot;</span>,</span>
<span id="cb182-28"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-28" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Precio promedio semanal&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Tiempo&quot;</span>) <span class="sc">+</span></span>
<span id="cb182-29"><a href="modelos-estacionales-en-series-de-tiempo.html#cb182-29" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-25-1.png" width="1050" /></p>
</div>
<div id="modelos-de-suavizamiento-y-holt-winters-en-serie-semanal-1" class="section level2 hasAnchor" number="4.17">
<h2><span class="header-section-number">4.17</span> <strong>Modelos de suavizamiento y Holt-Winters en serie semanal</strong><a href="modelos-estacionales-en-series-de-tiempo.html#modelos-de-suavizamiento-y-holt-winters-en-serie-semanal-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-1" tabindex="-1"></a><span class="co"># Horizonte de prueba</span></span>
<span id="cb183-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-2" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">length</span>(y_test_w)</span>
<span id="cb183-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-3" tabindex="-1"></a></span>
<span id="cb183-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-4" tabindex="-1"></a><span class="co"># Modelos de suavizamiento base</span></span>
<span id="cb183-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-5" tabindex="-1"></a><span class="co"># Suavizamiento exponencial simple (SES)</span></span>
<span id="cb183-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-6" tabindex="-1"></a>fit_ses_w <span class="ot">&lt;-</span> <span class="fu">ets</span>(y_train_w, <span class="at">model =</span> <span class="st">&quot;ANN&quot;</span>)</span>
<span id="cb183-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-7" tabindex="-1"></a>fc_ses_w  <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_ses_w, <span class="at">h =</span> h)</span>
<span id="cb183-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-8" tabindex="-1"></a></span>
<span id="cb183-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-9" tabindex="-1"></a><span class="co"># Holt: tendencia aditiva</span></span>
<span id="cb183-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-10" tabindex="-1"></a>fit_holt_w <span class="ot">&lt;-</span> <span class="fu">ets</span>(y_train_w, <span class="at">model =</span> <span class="st">&quot;AAN&quot;</span>)</span>
<span id="cb183-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-11" tabindex="-1"></a>fc_holt_w  <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_holt_w, <span class="at">h =</span> h)</span>
<span id="cb183-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-12" tabindex="-1"></a></span>
<span id="cb183-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-13" tabindex="-1"></a><span class="co"># Holt-Winters con función base stats::HoltWinters</span></span>
<span id="cb183-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-14" tabindex="-1"></a>fit_hwa_w <span class="ot">&lt;-</span> <span class="fu">HoltWinters</span>(y_train_w, <span class="at">seasonal =</span> <span class="st">&quot;additive&quot;</span>)</span>
<span id="cb183-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-15" tabindex="-1"></a>fit_hwm_w <span class="ot">&lt;-</span> <span class="fu">HoltWinters</span>(y_train_w, <span class="at">seasonal =</span> <span class="st">&quot;multiplicative&quot;</span>)</span>
<span id="cb183-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-16" tabindex="-1"></a></span>
<span id="cb183-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-17" tabindex="-1"></a><span class="co"># Generar pronósticos a h pasos</span></span>
<span id="cb183-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-18" tabindex="-1"></a>fc_hwa_w <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_hwa_w, <span class="at">h =</span> h)</span>
<span id="cb183-19"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-19" tabindex="-1"></a>fc_hwm_w <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_hwm_w, <span class="at">h =</span> h)</span>
<span id="cb183-20"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-20" tabindex="-1"></a></span>
<span id="cb183-21"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-21" tabindex="-1"></a><span class="co"># Resumen de parámetros de suavizamiento</span></span>
<span id="cb183-22"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-22" tabindex="-1"></a>pars_w <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb183-23"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-23" tabindex="-1"></a>  <span class="at">SES      =</span> fit_ses_w<span class="sc">$</span>par,</span>
<span id="cb183-24"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-24" tabindex="-1"></a>  <span class="at">Holt     =</span> fit_holt_w<span class="sc">$</span>par,</span>
<span id="cb183-25"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-25" tabindex="-1"></a>  <span class="at">HW_adi   =</span> fit_hwa_w<span class="sc">$</span>coefficients,</span>
<span id="cb183-26"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-26" tabindex="-1"></a>  <span class="at">HW_multi =</span> fit_hwm_w<span class="sc">$</span>coefficients</span>
<span id="cb183-27"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-27" tabindex="-1"></a>)</span>
<span id="cb183-28"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-28" tabindex="-1"></a></span>
<span id="cb183-29"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-29" tabindex="-1"></a>metodos_w <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb183-30"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-30" tabindex="-1"></a>  <span class="at">SES    =</span> fit_ses_w<span class="sc">$</span>method,</span>
<span id="cb183-31"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-31" tabindex="-1"></a>  <span class="at">Holt   =</span> fit_holt_w<span class="sc">$</span>method,</span>
<span id="cb183-32"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-32" tabindex="-1"></a>  <span class="at">HW_adi =</span> <span class="st">&quot;Holt-Winters aditivo (HoltWinters)&quot;</span>,</span>
<span id="cb183-33"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-33" tabindex="-1"></a>  <span class="at">HW_mul =</span> <span class="st">&quot;Holt-Winters multiplicativo (HoltWinters)&quot;</span></span>
<span id="cb183-34"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-34" tabindex="-1"></a>)</span>
<span id="cb183-35"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-35" tabindex="-1"></a></span>
<span id="cb183-36"><a href="modelos-estacionales-en-series-de-tiempo.html#cb183-36" tabindex="-1"></a><span class="fu">list</span>(<span class="at">pars =</span> pars_w, <span class="at">metodos =</span> metodos_w)</span></code></pre></div>
<pre><code>## $pars
## $pars$SES
##      alpha          l 
##  0.9998999 20.0661412 
## 
## $pars$Holt
##      alpha       beta        phi          l          b 
##  0.9998998  0.1131366  0.8000015 19.3507661  0.7318030 
## 
## $pars$HW_adi
##            a            b           s1           s2           s3           s4 
##  39.08244375   0.07882721  -7.65617219  -5.33129937  -2.12172776  -0.60521373 
##           s5           s6           s7           s8           s9          s10 
##   1.67227131   3.70855086   3.86297747   4.29730738   4.70950257   5.51286110 
##          s11          s12          s13          s14          s15          s16 
##   6.58108183   9.34052131  11.67282675  11.56985459  10.72690049  10.62915737 
##          s17          s18          s19          s20          s21          s22 
##  11.56624926  14.32396189  12.96493891  12.91210622  15.60833595  19.70484488 
##          s23          s24          s25          s26          s27          s28 
##  18.21542017  15.04288451   8.57289145   4.41893044   3.59468994   2.26948285 
##          s29          s30          s31          s32          s33          s34 
##   1.41348224   1.16589200   0.07345107  -2.59161738  -5.38569070  -6.81747767 
##          s35          s36          s37          s38          s39          s40 
##  -8.35116126 -10.31002086 -14.36805886 -15.48013931 -13.59119371 -14.10375330 
##          s41          s42          s43          s44          s45          s46 
## -12.98609882 -13.91879059 -12.80762063 -12.45344901 -10.91079687  -9.50278976 
##          s47          s48          s49          s50          s51          s52 
##  -7.48181474  -7.63951511  -9.66359895  -9.41494901  -8.19836375  -8.36815804 
## 
## $pars$HW_multi
##           a           b          s1          s2          s3          s4 
## 40.06957603  0.07882721  0.78984647  0.86149189  0.95592829  0.99520880 
##          s5          s6          s7          s8          s9         s10 
##  1.06150922  1.11859277  1.10742123  1.11547832  1.13362719  1.15295252 
##         s11         s12         s13         s14         s15         s16 
##  1.19755872  1.28051297  1.34512974  1.33136792  1.29845693  1.29564795 
##         s17         s18         s19         s20         s21         s22 
##  1.31337013  1.37966490  1.36129664  1.37542631  1.45910223  1.55273805 
##         s23         s24         s25         s26         s27         s28 
##  1.49801968  1.41880910  1.25803359  1.12986066  1.10809063  1.06878253 
##         s29         s30         s31         s32         s33         s34 
##  1.05012792  1.03448499  1.00251606  0.92562241  0.84794487  0.78549769 
##         s35         s36         s37         s38         s39         s40 
##  0.73966473  0.68969443  0.59218461  0.55743071  0.58537805  0.58407654 
##         s41         s42         s43         s44         s45         s46 
##  0.61227139  0.60444293  0.63415394  0.64018299  0.67488001  0.72564177 
##         s47         s48         s49         s50         s51         s52 
##  0.78927007  0.78769837  0.73692250  0.74269354  0.77194581  0.76652385 
## 
## 
## $metodos
##                                         SES 
##                                &quot;ETS(A,N,N)&quot; 
##                                        Holt 
##                               &quot;ETS(A,Ad,N)&quot; 
##                                      HW_adi 
##        &quot;Holt-Winters aditivo (HoltWinters)&quot; 
##                                      HW_mul 
## &quot;Holt-Winters multiplicativo (HoltWinters)&quot;</code></pre>
</div>
<div id="comparación-de-presición-fuera-de-muestra" class="section level2 hasAnchor" number="4.18">
<h2><span class="header-section-number">4.18</span> <strong>Comparación de presición fuera de muestra</strong><a href="modelos-estacionales-en-series-de-tiempo.html#comparación-de-presición-fuera-de-muestra" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-1" tabindex="-1"></a><span class="co"># Calcular métricas de error para cada modelo en el conjunto de prueba</span></span>
<span id="cb185-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-2" tabindex="-1"></a>acc_tbl <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb185-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-3" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">&quot;SES&quot;</span>,    <span class="fu">accuracy</span>(fc_ses_w,  y_test_w)),</span>
<span id="cb185-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-4" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">&quot;Holt&quot;</span>,   <span class="fu">accuracy</span>(fc_holt_w, y_test_w)),</span>
<span id="cb185-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-5" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">&quot;HW_adi&quot;</span>, <span class="fu">accuracy</span>(fc_hwa_w,  y_test_w)),</span>
<span id="cb185-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-6" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">&quot;HW_mul&quot;</span>, <span class="fu">accuracy</span>(fc_hwm_w,  y_test_w))</span>
<span id="cb185-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-7" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb185-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-8" tabindex="-1"></a>  <span class="fu">select</span>(model, RMSE, MAE, MAPE)</span>
<span id="cb185-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-9" tabindex="-1"></a></span>
<span id="cb185-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb185-10" tabindex="-1"></a>acc_tbl</span></code></pre></div>
<pre><code>##                   model      RMSE       MAE      MAPE
## Training set...1    SES  2.929804  1.928708  5.748854
## Test set...2        SES 33.778723 24.276695 34.505452
## Training set...3   Holt  2.902352  1.901817  5.638535
## Test set...4       Holt 34.593228 24.973105 35.456690
## Training set...5 HW_adi  2.984060  2.102575  6.453931
## Test set...6     HW_adi 20.668712 14.555681 20.798164
## Training set...7 HW_mul  2.846973  1.996849  6.036061
## Test set...8     HW_mul 18.997168 13.487363 19.577035</code></pre>
<p>El modelo Holt-Winters multiplicativo (HW_mul) es el mejor, porque presenta los errores más bajos (RMSE y MAPE) en la ventana de prueba.
Esto indica que la estacionalidad es proporcional al nivel de la serie (los picos crecen cuando el nivel general sube), lo cual es consistente con lo que se veia en el grafico.</p>
</div>
<div id="diagnostico-de-residuos-1" class="section level2 hasAnchor" number="4.19">
<h2><span class="header-section-number">4.19</span> <strong>Diagnostico de residuos</strong><a href="modelos-estacionales-en-series-de-tiempo.html#diagnostico-de-residuos-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vamos a confirmar que los residuos del modelo ganador (HW multiplicativo) se comportan como ruido blanco</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb187-1" tabindex="-1"></a>best_fc <span class="ot">&lt;-</span> fc_hwm_w  <span class="co"># ganador: Holt-Winters multiplicativo</span></span>
<span id="cb187-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb187-2" tabindex="-1"></a><span class="fu">checkresiduals</span>(best_fc<span class="sc">$</span>model)</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-28-1.png" width="1050" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from HoltWinters
## Q* = 76.422, df = 62, p-value = 0.1029
## 
## Model df: 0.   Total lags used: 62</code></pre>
<p>Al comparar los modelos de suavizamiento, Holt y Holt-Winters, se encontró que el Holt-Winters multiplicativo obtuvo los mejores resultados en la ventana de prueba, con los menores valores de RMSE (18.99) y MAPE (19.57 %).
Esto indica que la serie presenta una estacionalidad proporcional al nivel, es decir, las fluctuaciones son más amplias cuando los valores son altos.</p>
<p>El análisis de residuos respalda la adecuación del modelo: el p-valor = 0.1029 del test de Ljung-Box confirma que no existe autocorrelación significativa (residuos ≈ ruido blanco).
Por tanto, el modelo Holt-Winters multiplicativo logra capturar adecuadamente la tendencia y la estacionalidad de la serie semanal del precio promedio del Potato Red.</p>
</div>
<div id="pronostico-final-1" class="section level2 hasAnchor" number="4.20">
<h2><span class="header-section-number">4.20</span> <strong>Pronostico final</strong><a href="modelos-estacionales-en-series-de-tiempo.html#pronostico-final-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-1" tabindex="-1"></a><span class="co"># Reentrenar el modelo Holt-Winters multiplicativo con toda la serie semanal</span></span>
<span id="cb189-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-2" tabindex="-1"></a>fit_final_hw <span class="ot">&lt;-</span> <span class="fu">HoltWinters</span>(y_w, <span class="at">seasonal =</span> <span class="st">&quot;multiplicative&quot;</span>)</span>
<span id="cb189-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-3" tabindex="-1"></a></span>
<span id="cb189-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-4" tabindex="-1"></a><span class="co"># pronóstico a 52 semanas (≈ 1 año)</span></span>
<span id="cb189-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-5" tabindex="-1"></a>h_future <span class="ot">&lt;-</span> <span class="dv">52</span></span>
<span id="cb189-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-6" tabindex="-1"></a>fc_final_hw <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_final_hw, <span class="at">h =</span> h_future)</span>
<span id="cb189-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-7" tabindex="-1"></a></span>
<span id="cb189-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-8" tabindex="-1"></a><span class="co"># Visualizacion del pronóstico final</span></span>
<span id="cb189-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-9" tabindex="-1"></a><span class="fu">autoplot</span>(fc_final_hw) <span class="sc">+</span></span>
<span id="cb189-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-10" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb189-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-11" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Pronostico final Holt-Winters multiplicativo (52 semanas)&quot;</span>,</span>
<span id="cb189-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-12" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Precio promedio semanal&quot;</span>,</span>
<span id="cb189-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Tiempo&quot;</span></span>
<span id="cb189-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-14" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb189-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb189-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-29-1.png" width="1050" /></p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-1" tabindex="-1"></a><span class="co"># primeras filas de la tabla de pronostico</span></span>
<span id="cb190-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-2" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(</span>
<span id="cb190-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-3" tabindex="-1"></a>  <span class="at">Semana =</span> <span class="fu">time</span>(fc_final_hw<span class="sc">$</span>mean),</span>
<span id="cb190-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-4" tabindex="-1"></a>  <span class="at">Pronostico =</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(fc_final_hw<span class="sc">$</span>mean), <span class="dv">2</span>),</span>
<span id="cb190-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-5" tabindex="-1"></a>  <span class="at">LI_80 =</span> <span class="fu">round</span>(fc_final_hw<span class="sc">$</span>lower[,<span class="dv">1</span>], <span class="dv">2</span>),</span>
<span id="cb190-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-6" tabindex="-1"></a>  <span class="at">LS_80 =</span> <span class="fu">round</span>(fc_final_hw<span class="sc">$</span>upper[,<span class="dv">1</span>], <span class="dv">2</span>),</span>
<span id="cb190-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-7" tabindex="-1"></a>  <span class="at">LI_95 =</span> <span class="fu">round</span>(fc_final_hw<span class="sc">$</span>lower[,<span class="dv">2</span>], <span class="dv">2</span>),</span>
<span id="cb190-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-8" tabindex="-1"></a>  <span class="at">LS_95 =</span> <span class="fu">round</span>(fc_final_hw<span class="sc">$</span>upper[,<span class="dv">2</span>], <span class="dv">2</span>)</span>
<span id="cb190-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb190-9" tabindex="-1"></a>), <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##      Semana Pronostico LI_80 LS_80 LI_95 LS_95
## 1  8.961538      37.69 33.31 42.07 30.99 44.39
## 2  8.980769      40.88 35.05 46.72 31.96 49.81
## 3  9.000000      45.08 37.83 52.33 33.99 56.16
## 4  9.019231      47.46 39.09 55.83 34.66 60.26
## 5  9.038462      50.77 41.19 60.34 36.13 65.41
## 6  9.057692      55.25 44.31 66.19 38.52 71.98
## 7  9.076923      55.96 44.35 67.58 38.20 73.73
## 8  9.096154      55.31 43.30 67.32 36.95 73.67
## 9  9.115385      55.66 43.09 68.24 36.43 74.90
## 10 9.134615      58.37 44.76 71.99 37.55 79.20</code></pre>
</div>
<div id="conclusiones-1" class="section level2 hasAnchor" number="4.21">
<h2><span class="header-section-number">4.21</span> <strong>Conclusiones</strong><a href="modelos-estacionales-en-series-de-tiempo.html#conclusiones-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tras evaluar diferentes métodos de suavizamiento exponencial, se determinó que el modelo Holt-Winters multiplicativo fue el que presentó el mejor desempeño predictivo, con los menores errores (RMSE = 18.99 y MAPE = 19.6 %) en la ventana de prueba.</p>
<p>Este resultado confirma que la serie presenta estacionalidad proporcional al nivel, es decir, cuando el precio promedio del Potato Red aumenta, las fluctuaciones también lo hacen en la misma proporción.</p>
<p>Los residuos del modelo no mostraron autocorrelación significativa (p-valor = 0.1029), por lo que se concluye que el modelo explica adecuadamente la estructura temporal.</p>
<p>Con la serie completa y el modelo reentrenado, el pronóstico a 52 semanas muestra una tendencia oscilante con picos regulares y amplitud similar a la observada históricamente.
Las bandas de confianza (80 % y 95 %) reflejan un nivel de incertidumbre moderado, lo que otorga confianza en las estimaciones.</p>
<p>En conjunto, el método Holt-Winters multiplicativo demuestra ser una herramienta sólida y confiable para proyectar el comportamiento estacional del precio semanal del Potato Red.</p>
</div>
<div id="desarrollo-metodológico-y-justificación-de-decisiones-1" class="section level2 hasAnchor" number="4.22">
<h2><span class="header-section-number">4.22</span> <strong>Desarrollo metodológico y justificación de decisiones</strong><a href="modelos-estacionales-en-series-de-tiempo.html#desarrollo-metodológico-y-justificación-de-decisiones-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El proceso de aplicación del modelo de <strong>Holt-Winters</strong> a la serie de tiempo del <em>precio promedio del Potato Red</em> implicó diversos ajustes metodológicos debido a las características particulares de los datos.<br />
La variable de estudio correspondía a una <strong>serie diaria</strong> con una extensión superior a 2800 observaciones y frecuencia anual de 365. Si bien esta cantidad de datos representaba una fuente valiosa de información, también generó <strong>limitaciones computacionales</strong> al momento de ajustar modelos estacionales como <code>ets(model = "AAA")</code> o <code>hw(seasonal = "additive")</code>, debido a que la función <code>ets()</code> no está optimizada para manejar estacionalidades tan largas.</p>
<p>Durante los primeros intentos, el software arrojó el error <em>“Frequency too high”</em> o se quedaba ejecutando indefinidamente. Esto motivó una revisión del enfoque, identificando que la <strong>estacionalidad de interés</strong> no necesariamente se presentaba de manera diaria, sino más bien <strong>en ciclos semanales o mensuales</strong>, propios de los precios agrícolas.</p>
</div>
<div id="ajuste-de-la-frecuencia-temporal-1" class="section level2 hasAnchor" number="4.23">
<h2><span class="header-section-number">4.23</span> <strong>Ajuste de la frecuencia temporal</strong><a href="modelos-estacionales-en-series-de-tiempo.html#ajuste-de-la-frecuencia-temporal-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Como solución, se decidió <strong>agregar la serie a frecuencia semanal</strong>, calculando el promedio de los precios diarios.<br />
Esta decisión permitió conservar la forma cíclica de la serie (picos y valles regulares) y, al mismo tiempo, <strong>reducir la frecuencia de 365 a 52</strong>, lo cual hizo posible aplicar modelos estacionales de forma estable y con un tiempo de cómputo razonable.<br />
En la práctica, esto significó reconstruir la serie con una frecuencia semanal (<code>frequency = 52</code>), evitando la sobrecarga que impedía el ajuste de Holt-Winters en la versión original.</p>
</div>
<div id="modelos-aplicados-1" class="section level2 hasAnchor" number="4.24">
<h2><span class="header-section-number">4.24</span> <strong>Modelos aplicados</strong><a href="modelos-estacionales-en-series-de-tiempo.html#modelos-aplicados-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Una vez ajustada la frecuencia, se implementaron cuatro modelos de suavizamiento:</p>
<ol style="list-style-type: decimal">
<li><strong>Suavizamiento exponencial simple (SES)</strong> – Captura únicamente el nivel de la serie.<br />
</li>
<li><strong>Método de Holt</strong> – Incorpora tendencia aditiva.<br />
</li>
<li><strong>Holt-Winters aditivo</strong> – Considera tendencia y estacionalidad de amplitud constante.<br />
</li>
<li><strong>Holt-Winters multiplicativo</strong> – Considera estacionalidad proporcional al nivel.</li>
</ol>
<p>Debido a los errores recurrentes con <code>ets()</code> y <code>hw()</code>, se optó finalmente por la función <strong><code>stats::HoltWinters()</code></strong>, que permite ajustar modelos estacionales de manera más estable con series largas o de alta frecuencia.</p>
</div>
<div id="validación-del-modelo-1" class="section level2 hasAnchor" number="4.25">
<h2><span class="header-section-number">4.25</span> <strong>Validación del modelo</strong><a href="modelos-estacionales-en-series-de-tiempo.html#validación-del-modelo-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La serie semanal se dividió en un conjunto de <strong>entrenamiento (80%)</strong> y otro de <strong>prueba (20%)</strong>, correspondiente aproximadamente a un año de observaciones.<br />
Con esta división, se evaluó el desempeño predictivo de cada modelo mediante métricas como <strong>RMSE</strong>, <strong>MAE</strong> y <strong>MAPE</strong>.</p>
<p>Los resultados mostraron que el <strong>modelo Holt-Winters multiplicativo</strong> presentó el mejor desempeño (RMSE = 18.99, MAPE = 19.6%), superando a las versiones aditiva, Holt y SES.<br />
Esto indica que la estacionalidad es <strong>proporcional al nivel</strong> de la serie: cuando los precios son altos, las fluctuaciones semanales también lo son.</p>
</div>
<div id="diagnóstico-de-residuos-1" class="section level2 hasAnchor" number="4.26">
<h2><span class="header-section-number">4.26</span> <strong>Diagnóstico de residuos</strong><a href="modelos-estacionales-en-series-de-tiempo.html#diagnóstico-de-residuos-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para validar el ajuste, se analizaron los residuos del modelo Holt-Winters multiplicativo.<br />
El test de <strong>Ljung-Box (p-valor = 0.1029)</strong> indicó ausencia de autocorrelación significativa, lo cual demuestra que el modelo logra capturar adecuadamente la tendencia y la estacionalidad de los datos.<br />
Además, el gráfico ACF de los residuos no mostró patrones sistemáticos, confirmando que el error se comporta como <strong>ruido blanco</strong>.</p>
</div>
<div id="pronóstico-final-1" class="section level2 hasAnchor" number="4.27">
<h2><span class="header-section-number">4.27</span> <strong>Pronóstico final</strong><a href="modelos-estacionales-en-series-de-tiempo.html#pronóstico-final-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Con base en el modelo seleccionado, se reentrenó la serie completa y se realizó un <strong>pronóstico a 52 semanas</strong> (equivalente a un año).<br />
El resultado mostró una evolución oscilante, con picos estacionales regulares y una amplitud coherente con los patrones históricos observados.<br />
Las bandas de confianza del 80% y 95% se mantuvieron en rangos moderados, reflejando un nivel de incertidumbre aceptable.</p>
</div>
<div id="conclusión-integradora-1" class="section level2 hasAnchor" number="4.28">
<h2><span class="header-section-number">4.28</span> <strong>Conclusión integradora</strong><a href="modelos-estacionales-en-series-de-tiempo.html#conclusión-integradora-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En síntesis, el desarrollo de este modelo implicó un proceso iterativo de ajuste y validación.<br />
Se comprobó que aplicar Holt-Winters directamente sobre la serie diaria era impracticable por su frecuencia alta, por lo que fue necesario <strong>agregar la serie a frecuencia semanal</strong> para estabilizar el modelo.<br />
Este cambio permitió aplicar el método de forma exitosa y obtener resultados coherentes, concluyendo que el <strong>modelo Holt-Winters multiplicativo</strong> es una herramienta sólida para pronosticar el comportamiento estacional del precio del <em>Potato Red</em>, combinando buena precisión y consistencia temporal.</p>
</div>
<div id="ajuste-e-interpretación-del-modelo-arimasarima---box-jenkins-arima" class="section level2 hasAnchor" number="4.29">
<h2><span class="header-section-number">4.29</span> <strong>4. Ajuste e interpretación del modelo ARIMA/SARIMA - Box-Jenkins (ARIMA)</strong><a href="modelos-estacionales-en-series-de-tiempo.html#ajuste-e-interpretación-del-modelo-arimasarima---box-jenkins-arima" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-1" tabindex="-1"></a><span class="co"># Serie semanal en log</span></span>
<span id="cb192-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-2" tabindex="-1"></a>y_w_log      <span class="ot">&lt;-</span> <span class="fu">log</span>(y_w)</span>
<span id="cb192-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-3" tabindex="-1"></a>y_train_w_log <span class="ot">&lt;-</span> <span class="fu">log</span>(y_train_w)</span>
<span id="cb192-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-4" tabindex="-1"></a>y_test_w_log  <span class="ot">&lt;-</span> <span class="fu">log</span>(y_test_w)</span>
<span id="cb192-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-5" tabindex="-1"></a></span>
<span id="cb192-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-6" tabindex="-1"></a><span class="co"># Horizonte</span></span>
<span id="cb192-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-7" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">length</span>(y_test_w)</span>
<span id="cb192-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-8" tabindex="-1"></a>lengths <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">total =</span> <span class="fu">length</span>(y_w_log), <span class="at">train =</span> <span class="fu">length</span>(y_train_w_log), <span class="at">test =</span> <span class="fu">length</span>(y_test_w))</span>
<span id="cb192-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb192-9" tabindex="-1"></a>lengths</span></code></pre></div>
<pre><code>## total train  test 
##   414   362    52</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb194-1" tabindex="-1"></a><span class="fu">ggAcf</span>(y_train_w_log)  <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ACF log semanal (train)&quot;</span>)</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-31-1.png" width="1050" /></p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb195-1" tabindex="-1"></a><span class="fu">ggPacf</span>(y_train_w_log) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;PACF log semanal (train)&quot;</span>)</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-31-2.png" width="1050" /></p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-1" tabindex="-1"></a><span class="co"># Candidato 1: ARIMA no estacional</span></span>
<span id="cb196-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-2" tabindex="-1"></a>fit_ns <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(</span>
<span id="cb196-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-3" tabindex="-1"></a>  y_train_w_log,</span>
<span id="cb196-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-4" tabindex="-1"></a>  <span class="at">seasonal      =</span> <span class="cn">FALSE</span>,</span>
<span id="cb196-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-5" tabindex="-1"></a>  <span class="at">stepwise      =</span> <span class="cn">TRUE</span>,</span>
<span id="cb196-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-6" tabindex="-1"></a>  <span class="at">approximation =</span> <span class="cn">TRUE</span>,</span>
<span id="cb196-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-7" tabindex="-1"></a>  <span class="at">allowmean     =</span> <span class="cn">TRUE</span>,</span>
<span id="cb196-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-8" tabindex="-1"></a>  <span class="at">allowdrift    =</span> <span class="cn">TRUE</span></span>
<span id="cb196-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-9" tabindex="-1"></a>)</span>
<span id="cb196-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-10" tabindex="-1"></a></span>
<span id="cb196-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-11" tabindex="-1"></a><span class="co"># Candidato 2:</span></span>
<span id="cb196-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-12" tabindex="-1"></a></span>
<span id="cb196-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-13" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">frequency</span>(y_train_w_log)  </span>
<span id="cb196-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-14" tabindex="-1"></a>D_est <span class="ot">&lt;-</span> <span class="fu">nsdiffs</span>(y_train_w_log)</span>
<span id="cb196-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-15" tabindex="-1"></a></span>
<span id="cb196-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-16" tabindex="-1"></a>y_train_w_log_sdiff <span class="ot">&lt;-</span> <span class="fu">diff</span>(y_train_w_log, <span class="at">lag =</span> m, <span class="at">differences =</span> D_est)</span>
<span id="cb196-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-17" tabindex="-1"></a></span>
<span id="cb196-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-18" tabindex="-1"></a>fit_seas_fast <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(</span>
<span id="cb196-19"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-19" tabindex="-1"></a>  y_train_w_log_sdiff,</span>
<span id="cb196-20"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-20" tabindex="-1"></a>  <span class="at">seasonal      =</span> <span class="cn">FALSE</span>,      </span>
<span id="cb196-21"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-21" tabindex="-1"></a>  <span class="at">stepwise      =</span> <span class="cn">TRUE</span>,</span>
<span id="cb196-22"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-22" tabindex="-1"></a>  <span class="at">approximation =</span> <span class="cn">TRUE</span>,</span>
<span id="cb196-23"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-23" tabindex="-1"></a>  <span class="at">max.p         =</span> <span class="dv">5</span>,</span>
<span id="cb196-24"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-24" tabindex="-1"></a>  <span class="at">max.q         =</span> <span class="dv">5</span>,</span>
<span id="cb196-25"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-25" tabindex="-1"></a>  <span class="at">max.order     =</span> <span class="dv">8</span>,</span>
<span id="cb196-26"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-26" tabindex="-1"></a>  <span class="at">allowmean     =</span> <span class="cn">TRUE</span>,</span>
<span id="cb196-27"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-27" tabindex="-1"></a>  <span class="at">allowdrift    =</span> <span class="cn">TRUE</span></span>
<span id="cb196-28"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-28" tabindex="-1"></a>)</span>
<span id="cb196-29"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-29" tabindex="-1"></a></span>
<span id="cb196-30"><a href="modelos-estacionales-en-series-de-tiempo.html#cb196-30" tabindex="-1"></a>fit_seas_fast</span></code></pre></div>
<pre><code>## Series: y_train_w_log_sdiff 
## ARIMA(1,0,0) with zero mean 
## 
## Coefficients:
##          ar1
##       0.9562
## s.e.  0.0163
## 
## sigma^2 = 0.009812:  log likelihood = 276.14
## AIC=-548.29   AICc=-548.25   BIC=-540.82</code></pre>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-1" tabindex="-1"></a><span class="co"># Extraer orden no estacional del modelo rapido sobre la serie s-diferenciada</span></span>
<span id="cb198-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-2" tabindex="-1"></a>ord <span class="ot">&lt;-</span> <span class="fu">arimaorder</span>(fit_seas_fast)        </span>
<span id="cb198-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-3" tabindex="-1"></a>p <span class="ot">&lt;-</span> ord[<span class="st">&quot;p&quot;</span>]; d <span class="ot">&lt;-</span> <span class="dv">0</span>; q <span class="ot">&lt;-</span> ord[<span class="st">&quot;q&quot;</span>]</span>
<span id="cb198-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-4" tabindex="-1"></a></span>
<span id="cb198-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-5" tabindex="-1"></a><span class="co"># Periodo estacional y orden estacional detectado</span></span>
<span id="cb198-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-6" tabindex="-1"></a>m     <span class="ot">&lt;-</span> <span class="fu">frequency</span>(y_train_w_log)</span>
<span id="cb198-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-7" tabindex="-1"></a>D_est <span class="ot">&lt;-</span> <span class="fu">nsdiffs</span>(y_train_w_log) </span>
<span id="cb198-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-8" tabindex="-1"></a></span>
<span id="cb198-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-9" tabindex="-1"></a><span class="co">#  Ajuste SARIMA equivalente sobre la serie en log SIN diferenciar manualmente</span></span>
<span id="cb198-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-10" tabindex="-1"></a><span class="co">#    SARIMA(p,d,q)(P=0, D=D_est, Q=0)[m], sin media (zero mean) como indico el modelo rapido</span></span>
<span id="cb198-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-11" tabindex="-1"></a>fit_seas_refit <span class="ot">&lt;-</span> <span class="fu">Arima</span>(</span>
<span id="cb198-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-12" tabindex="-1"></a>  y_train_w_log,</span>
<span id="cb198-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-13" tabindex="-1"></a>  <span class="at">order    =</span> <span class="fu">c</span>(p, d, q),</span>
<span id="cb198-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-14" tabindex="-1"></a>  <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, D_est, <span class="dv">0</span>), <span class="at">period =</span> m),</span>
<span id="cb198-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-15" tabindex="-1"></a>  <span class="at">include.mean =</span> <span class="cn">FALSE</span></span>
<span id="cb198-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-16" tabindex="-1"></a>)</span>
<span id="cb198-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-17" tabindex="-1"></a></span>
<span id="cb198-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb198-18" tabindex="-1"></a>fit_seas_refit</span></code></pre></div>
<pre><code>## Series: y_train_w_log 
## ARIMA(1,0,0)(0,1,0)[52] 
## 
## Coefficients:
##          ar1
##       0.9562
## s.e.  0.0163
## 
## sigma^2 = 0.009814:  log likelihood = 276.15
## AIC=-548.3   AICc=-548.26   BIC=-540.82</code></pre>
</div>
<div id="pronostico-a-h-pasos-y-metricas-rmsemaemape" class="section level2 hasAnchor" number="4.30">
<h2><span class="header-section-number">4.30</span> <strong>Pronostico a h pasos y metricas RMSE/MAE/MAPE</strong><a href="modelos-estacionales-en-series-de-tiempo.html#pronostico-a-h-pasos-y-metricas-rmsemaemape" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-1" tabindex="-1"></a><span class="co"># 1) Pronostico en log y transformacion a escala original</span></span>
<span id="cb200-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-2" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">length</span>(y_test_w)</span>
<span id="cb200-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-3" tabindex="-1"></a>fc_seas_log <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_seas_refit, <span class="at">h =</span> h)</span>
<span id="cb200-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-4" tabindex="-1"></a></span>
<span id="cb200-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-5" tabindex="-1"></a>fc_seas <span class="ot">&lt;-</span> fc_seas_log</span>
<span id="cb200-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-6" tabindex="-1"></a>fc_seas<span class="sc">$</span>mean  <span class="ot">&lt;-</span> <span class="fu">exp</span>(fc_seas_log<span class="sc">$</span>mean)</span>
<span id="cb200-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-7" tabindex="-1"></a>fc_seas<span class="sc">$</span>lower <span class="ot">&lt;-</span> <span class="fu">exp</span>(fc_seas_log<span class="sc">$</span>lower)</span>
<span id="cb200-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-8" tabindex="-1"></a>fc_seas<span class="sc">$</span>upper <span class="ot">&lt;-</span> <span class="fu">exp</span>(fc_seas_log<span class="sc">$</span>upper)</span>
<span id="cb200-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-9" tabindex="-1"></a></span>
<span id="cb200-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-10" tabindex="-1"></a><span class="co"># 2) Comparacion</span></span>
<span id="cb200-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-11" tabindex="-1"></a>tiene_ns <span class="ot">&lt;-</span> <span class="fu">exists</span>(<span class="st">&quot;fc_ns&quot;</span>)</span>
<span id="cb200-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-12" tabindex="-1"></a></span>
<span id="cb200-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-13" tabindex="-1"></a><span class="cf">if</span> (tiene_ns) {</span>
<span id="cb200-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-14" tabindex="-1"></a>  acc_tbl_arima <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb200-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-15" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">&quot;ARIMA_ns&quot;</span>,  <span class="fu">accuracy</span>(fc_ns,   y_test_w)),</span>
<span id="cb200-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-16" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">&quot;SARIMA_52&quot;</span>, <span class="fu">accuracy</span>(fc_seas, y_test_w))</span>
<span id="cb200-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-17" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">select</span>(model, RMSE, MAE, MAPE)</span>
<span id="cb200-18"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-18" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb200-19"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-19" tabindex="-1"></a>  acc_tbl_arima <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb200-20"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-20" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">model =</span> <span class="st">&quot;SARIMA_52&quot;</span>, <span class="fu">accuracy</span>(fc_seas, y_test_w))</span>
<span id="cb200-21"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-21" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">select</span>(model, RMSE, MAE, MAPE)</span>
<span id="cb200-22"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-22" tabindex="-1"></a>}</span>
<span id="cb200-23"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-23" tabindex="-1"></a></span>
<span id="cb200-24"><a href="modelos-estacionales-en-series-de-tiempo.html#cb200-24" tabindex="-1"></a>acc_tbl_arima</span></code></pre></div>
<pre><code>##                  model        RMSE         MAE     MAPE
## Training set SARIMA_52  0.09152501  0.06528711  1.90487
## Test set     SARIMA_52 18.80827374 15.08098880 25.67046</code></pre>
</div>
<div id="diagnostico-de-residuos-2" class="section level2 hasAnchor" number="4.31">
<h2><span class="header-section-number">4.31</span> <strong>Diagnostico de residuos</strong><a href="modelos-estacionales-en-series-de-tiempo.html#diagnostico-de-residuos-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb202-1" tabindex="-1"></a><span class="co"># Evaluacion de residuos del modelo SARIMA</span></span>
<span id="cb202-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb202-2" tabindex="-1"></a><span class="fu">checkresiduals</span>(fit_seas_refit)</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-34-1.png" width="1050" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,0,0)(0,1,0)[52]
## Q* = 152.72, df = 71, p-value = 6.441e-08
## 
## Model df: 1.   Total lags used: 72</code></pre>
</div>
<div id="pronostico-final-sarima-10001052" class="section level2 hasAnchor" number="4.32">
<h2><span class="header-section-number">4.32</span> <strong>Pronostico final Sarima (1,0,0)(0,1,0)[52]</strong><a href="modelos-estacionales-en-series-de-tiempo.html#pronostico-final-sarima-10001052" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-1" tabindex="-1"></a><span class="co"># Pronostico a 52 semanas</span></span>
<span id="cb204-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-2" tabindex="-1"></a>fc_final <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_seas_refit, <span class="at">h =</span> <span class="dv">52</span>)</span>
<span id="cb204-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-3" tabindex="-1"></a></span>
<span id="cb204-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-4" tabindex="-1"></a><span class="co"># Volver a escala original</span></span>
<span id="cb204-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-5" tabindex="-1"></a>fc_final_exp <span class="ot">&lt;-</span> fc_final</span>
<span id="cb204-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-6" tabindex="-1"></a>fc_final_exp<span class="sc">$</span>mean  <span class="ot">&lt;-</span> <span class="fu">exp</span>(fc_final<span class="sc">$</span>mean)</span>
<span id="cb204-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-7" tabindex="-1"></a>fc_final_exp<span class="sc">$</span>lower <span class="ot">&lt;-</span> <span class="fu">exp</span>(fc_final<span class="sc">$</span>lower)</span>
<span id="cb204-8"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-8" tabindex="-1"></a>fc_final_exp<span class="sc">$</span>upper <span class="ot">&lt;-</span> <span class="fu">exp</span>(fc_final<span class="sc">$</span>upper)</span>
<span id="cb204-9"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-9" tabindex="-1"></a></span>
<span id="cb204-10"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-10" tabindex="-1"></a><span class="co"># OPCION A: Grafico simple del pronostico (incluye bandas 80% y 95% automaticamente)</span></span>
<span id="cb204-11"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-11" tabindex="-1"></a><span class="fu">autoplot</span>(fc_final_exp) <span class="sc">+</span></span>
<span id="cb204-12"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-12" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb204-13"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-13" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">&quot;Pronostico final SARIMA(1,0,0)(0,1,0)[52]&quot;</span>,</span>
<span id="cb204-14"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-14" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">&quot;Proyeccion de precios semanales con intervalos de confianza&quot;</span>,</span>
<span id="cb204-15"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-15" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Tiempo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Precio promedio semanal&quot;</span></span>
<span id="cb204-16"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-16" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb204-17"><a href="modelos-estacionales-en-series-de-tiempo.html#cb204-17" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="04-application_files/figure-html/unnamed-chunk-35-1.png" width="1050" /></p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb205-1" tabindex="-1"></a><span class="co"># Ajuste automático con comparación AIC/BIC</span></span>
<span id="cb205-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb205-2" tabindex="-1"></a></span>
<span id="cb205-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb205-3" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">ts</span>(potatored<span class="sc">$</span>Average, <span class="at">frequency =</span> <span class="dv">7</span>)</span>
<span id="cb205-4"><a href="modelos-estacionales-en-series-de-tiempo.html#cb205-4" tabindex="-1"></a>fit_arima <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(</span>
<span id="cb205-5"><a href="modelos-estacionales-en-series-de-tiempo.html#cb205-5" tabindex="-1"></a>y, <span class="at">seasonal =</span> <span class="cn">TRUE</span>, <span class="at">stepwise =</span> <span class="cn">FALSE</span>, <span class="at">approximation =</span> <span class="cn">FALSE</span></span>
<span id="cb205-6"><a href="modelos-estacionales-en-series-de-tiempo.html#cb205-6" tabindex="-1"></a>)</span>
<span id="cb205-7"><a href="modelos-estacionales-en-series-de-tiempo.html#cb205-7" tabindex="-1"></a>fit_arima</span></code></pre></div>
<pre><code>## Series: y 
## ARIMA(1,1,0) 
## 
## Coefficients:
##           ar1
##       -0.2051
## s.e.   0.0190
## 
## sigma^2 = 4.054:  log likelihood = -5848.36
## AIC=11700.72   AICc=11700.73   BIC=11712.66</code></pre>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb207-1" tabindex="-1"></a><span class="fu">AIC</span>(fit_arima); <span class="fu">BIC</span>(fit_arima)</span></code></pre></div>
<pre><code>## [1] 11700.72</code></pre>
<pre><code>## [1] 11712.56</code></pre>
</div>
<div id="interpretación-del-modelo" class="section level2 hasAnchor" number="4.33">
<h2><span class="header-section-number">4.33</span> <strong>4.1 Interpretación del modelo</strong><a href="modelos-estacionales-en-series-de-tiempo.html#interpretación-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Los parámetros estimados
(𝑝,𝑑,𝑞)
(p,d,q) reflejan la dependencia autorregresiva y el componente de promedio móvil, ambos esenciales para capturar la dinámica de corto plazo de la serie.</p>
<p>El parámetro
𝑑d —y 𝐷
D si se incluye una componente estacional— controla la diferenciación aplicada para garantizar la estacionariedad de la media, permitiendo que la serie cumpla los supuestos de los modelos lineales autorregresivos.</p>
<p>En este contexto, los valores obtenidos evidencian una estructura temporal que combina persistencia en los precios con fluctuaciones regulares atribuibles a factores estacionales.</p>
</div>
<div id="reflexión-y-justificación-del-proceso-boxjenkins" class="section level2 hasAnchor" number="4.34">
<h2><span class="header-section-number">4.34</span> <strong>4.2 Reflexión y justificación del proceso Box–Jenkins</strong><a href="modelos-estacionales-en-series-de-tiempo.html#reflexión-y-justificación-del-proceso-boxjenkins" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta fase se implementó la metodología Box–Jenkins con el propósito de identificar un modelo autorregresivo e integrado de medias móviles (ARIMA) que representara adecuadamente la dinámica temporal del precio promedio semanal del Potato Red y permitiera realizar pronósticos confiables a corto y mediano plazo.</p>
<p>Se inició el proceso con una transformación logarítmica de la serie semanal, buscando estabilizar la varianza y cumplir con los supuestos de linealidad.</p>
<p>Posteriormente, se determinó la necesidad de aplicar una diferencia estacional de orden 1, identificada mediante la función nsdiffs() y la prueba OCSB, que confirmó una estacionalidad anual de 52 semanas.</p>
<p>Este paso fue crucial para asegurar la estacionariedad de la serie antes del ajuste final de los modelos ARIMA y SARIMA, condición indispensable dentro del enfoque Box–Jenkins.</p>
</div>
<div id="ajustes-metodológicos-y-rendimiento-computacional" class="section level2 hasAnchor" number="4.35">
<h2><span class="header-section-number">4.35</span> <strong>4.3 Ajustes metodológicos y rendimiento computacional</strong><a href="modelos-estacionales-en-series-de-tiempo.html#ajustes-metodológicos-y-rendimiento-computacional" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Durante la primera ejecución de auto.arima() con búsqueda estacional completa, se observó que el proceso requería un tiempo computacional elevado, consecuencia directa de la longitud de la serie y del gran número de combinaciones posibles entre parámetros.</p>
<p>Para optimizar el rendimiento y mantener la rigurosidad estadística, se desarrolló una estrategia de ajuste en dos etapas complementarias:</p>
<ol style="list-style-type: lower-alpha">
<li>Primera etapa:</li>
</ol>
<p>Se modeló la serie ya diferenciada estacionalmente (y_train_w_log_sdiff) sin incluir la componente estacional explícita.</p>
<p>Este enfoque permitió acelerar la búsqueda y obtener una estructura preliminar AR(1) con coeficiente φ ≈ 0.956, evidenciando la dependencia dominante sin saturar los recursos computacionales.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Segunda etapa:</li>
</ol>
<p>Se refinó el modelo, ajustando la serie logarítmica original e incorporando la estacionalidad detectada, obteniendo finalmente el modelo SARIMA(1,0,0)(0,1,0)[52].</p>
<p>Este procedimiento permitió mantener la coherencia metodológica del enfoque Box–Jenkins, optimizando la eficiencia y la reproducibilidad del proceso analítico.</p>
</div>
<div id="evaluación-del-modelo" class="section level2 hasAnchor" number="4.36">
<h2><span class="header-section-number">4.36</span> <strong>4.4 Evaluación del modelo</strong><a href="modelos-estacionales-en-series-de-tiempo.html#evaluación-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El modelo SARIMA(1,0,0)(0,1,0)[52] mostró un excelente ajuste dentro de muestra (MAPE ≈ 1.9 %) y un desempeño razonable fuera de muestra (MAPE ≈ 25.7 %).</p>
<p>El coeficiente AR(1), cercano a 1, evidencia una alta persistencia temporal, indicando que los precios semanales del Potato Red dependen fuertemente de los valores previos.</p>
<p>Al analizar los residuos mediante checkresiduals(), la prueba de Ljung–Box arrojó un p-valor &lt; 0.05, lo que sugiere la presencia de autocorrelación remanente.</p>
<p>Este hallazgo abre la posibilidad de incorporar términos adicionales —por ejemplo, un componente MA o parámetros estacionales extra— para capturar dependencias de mayor orden.</p>
<p>Aun así, los residuos no mostraron tendencias sistemáticas ni heterocedasticidad marcada, indicando un buen ajuste general del modelo y un comportamiento próximo al ruido blanco.</p>
</div>
<div id="reflexión-metodológica-final" class="section level2 hasAnchor" number="4.37">
<h2><span class="header-section-number">4.37</span> <strong>4.5 Reflexión metodológica final</strong><a href="modelos-estacionales-en-series-de-tiempo.html#reflexión-metodológica-final" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La aplicación del enfoque Box–Jenkins permitió equilibrar rigor estadístico y eficiencia computacional, demostrando que, incluso en series extensas con fuerte estacionalidad, es posible construir modelos parsimoniosos, interpretables y funcionales.</p>
<p>Este proceso refuerza la importancia de documentar y justificar cada decisión metodológica, desde la transformación logarítmica hasta la diferenciación y la selección del modelo final.</p>
<p>El modelo obtenido captura adecuadamente la tendencia y la estacionalidad del precio semanal del Potato Red, proporcionando una base sólida para pronósticos confiables.</p>
<p>Se concluye que este tipo de modelado contribuye de manera significativa a la planificación de abastecimiento y estrategias de fijación de precios agrícolas, ofreciendo un soporte cuantitativo a la toma de decisiones.</p>
</div>
<div id="evaluación-del-modelo-1" class="section level2 hasAnchor" number="4.38">
<h2><span class="header-section-number">4.38</span> <strong>5. EVALUACIÓN DEL MODELO</strong><a href="modelos-estacionales-en-series-de-tiempo.html#evaluación-del-modelo-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La validación se centró en tres frentes:</p>
<p>4.1 Diagnóstico de residuos: ausencia de autocorrelación (ACF/PACF de residuos sin picos significativos), media cercana a cero y homocedasticidad razonable.</p>
<p>4.2 Criterios de información: AIC/BIC del modelo final comparados con alternativas cercanas (p.ej., variaciones de
𝑝p, 𝑞q o componente estacional).</p>
<p>4.3 Error de pronóstico (si se dispone de holdout): métricas como RMSE, MAE y MAPE sobre un conjunto de prueba temporal.</p>
<p>Conclusión de evaluación. El modelo seleccionado mostró residuos compatibles con ruido blanco y valores de AIC/BIC competitivos, lo que sugiere ajuste adecuado sin sobreparametrización. En presencia de estacionalidad pronunciada, un SARIMA suele mejorar aún más AIC/BIC y diagnóstico residual.</p>
</div>
<div id="pronostico-y-conclusiones" class="section level2 hasAnchor" number="4.39">
<h2><span class="header-section-number">4.39</span> <strong>6. PRONOSTICO Y CONCLUSIONES</strong><a href="modelos-estacionales-en-series-de-tiempo.html#pronostico-y-conclusiones" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Con el modelo validado, se generaron pronósticos puntuales e intervalares mediante forecast() (o predict()), a un horizonte operativo (p.ej., 30 días). Los intervalos de confianza reflejan la incertidumbre asociada a la varianza del error y a la propagación en el tiempo.</p>
<p>Pronóstico final</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="modelos-estacionales-en-series-de-tiempo.html#cb210-1" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb210-2"><a href="modelos-estacionales-en-series-de-tiempo.html#cb210-2" tabindex="-1"></a>fc <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">forecast</span>(fit_arima, <span class="at">h =</span> h)</span>
<span id="cb210-3"><a href="modelos-estacionales-en-series-de-tiempo.html#cb210-3" tabindex="-1"></a>fc</span></code></pre></div>
<pre><code>##          Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 413.7143             36 33.41964 38.58036 32.05368 39.94632
## 413.8571             36 32.70369 39.29631 30.95873 41.04127
## 414.0000             36 32.05918 39.94082 29.97304 42.02696
## 414.1429             36 31.51683 40.48317 29.14359 42.85641
## 414.2857             36 31.03139 40.96861 28.40117 43.59883
## 414.4286             36 30.58970 41.41030 27.72566 44.27434
## 414.5714             36 30.18137 41.81863 27.10118 44.89882
## 414.7143             36 29.79989 42.20011 26.51775 45.48225
## 414.8571             36 29.44055 42.55945 25.96819 46.03181
## 415.0000             36 29.09991 42.90009 25.44722 46.55278
## 415.1429             36 28.77530 43.22470 24.95078 47.04922
## 415.2857             36 28.46467 43.53533 24.47571 47.52429
## 415.4286             36 28.16635 43.83365 24.01946 47.98054
## 415.5714             36 27.87897 44.12103 23.57996 48.42004
## 415.7143             36 27.60143 44.39857 23.15549 48.84451
## 415.8571             36 27.33276 44.66724 22.74461 49.25539
## 416.0000             36 27.07218 44.92782 22.34608 49.65392
## 416.1429             36 26.81899 45.18101 21.95886 50.04114
## 416.2857             36 26.57260 45.42740 21.58204 50.41796
## 416.4286             36 26.33249 45.66751 21.21482 50.78518
## 416.5714             36 26.09819 45.90181 20.85650 51.14350
## 416.7143             36 25.86932 46.13068 20.50646 51.49354
## 416.8571             36 25.64550 46.35450 20.16416 51.83584
## 417.0000             36 25.42642 46.57358 19.82910 52.17090
## 417.1429             36 25.21179 46.78821 19.50085 52.49915
## 417.2857             36 25.00134 46.99866 19.17900 52.82100
## 417.4286             36 24.79485 47.20515 18.86320 53.13680
## 417.5714             36 24.59209 47.40791 18.55311 53.44689
## 417.7143             36 24.39287 47.60713 18.24843 53.75157
## 417.8571             36 24.19702 47.80298 17.94890 54.05110</code></pre>
</div>
<div id="conclusiones-generales-finales" class="section level2 hasAnchor" number="4.40">
<h2><span class="header-section-number">4.40</span> <strong>7. CONCLUSIONES GENERALES FINALES</strong><a href="modelos-estacionales-en-series-de-tiempo.html#conclusiones-generales-finales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>La serie del “Potato Red” presenta no estacionariedad inicial (tendencia y estacionalidad), que se corrige con log + diferenciación.</p></li>
<li><p>La dependencia temporal y la estacionalidad justifican el uso de ARIMA/SARIMA.</p></li>
<li><p>El modelo seleccionado vía AIC/BIC exhibe residuos tipo ruido blanco y métricas de error razonables, lo que respalda su uso para planificación de abastecimiento y precios.</p></li>
<li><p>Recomendaciones: evaluar SARIMA si la estacionalidad es fuerte, comparar con ETS y considerar ARIMAX si se dispone de variables exógenas (oferta, clima, transporte).</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="pronóstico-de-demanda-holtwinters.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04-application.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
